import { MigrateUpArgs, MigrateDownArgs, sql } from '@payloadcms/db-postgres'

export async function up({ db, payload, req }: MigrateUpArgs): Promise<void> {
  await db.execute(sql`
   CREATE TYPE "public"."enum_pages_blocks_banner9_social_media_links_type" AS ENUM('reference', 'custom');
  CREATE TYPE "public"."enum_pages_blocks_banner9_font_family" AS ENUM('default', 'Arial, sans-serif', '"Times New Roman", serif', 'Georgia, serif', 'Verdana, sans-serif', 'Helvetica, Arial, sans-serif', '"Courier New", monospace', '"Roboto", sans-serif', '"Open Sans", sans-serif', '"Lato", sans-serif', '"Montserrat", sans-serif', '"Playfair Display", serif', '"Inter", sans-serif', '"Poppins", sans-serif', '"Raleway", sans-serif');
  CREATE TYPE "public"."enum_pages_blocks_blog1_tabs_content_type" AS ENUM('reference', 'custom');
  CREATE TYPE "public"."enum_pages_blocks_blog1_font_family" AS ENUM('default', 'Arial, sans-serif', '"Times New Roman", serif', 'Georgia, serif', 'Verdana, sans-serif', 'Helvetica, Arial, sans-serif', '"Courier New", monospace', '"Roboto", sans-serif', '"Open Sans", sans-serif', '"Lato", sans-serif', '"Montserrat", sans-serif', '"Playfair Display", serif', '"Inter", sans-serif', '"Poppins", sans-serif', '"Raleway", sans-serif');
  CREATE TYPE "public"."enum_pages_blocks_blog5_tabs_content_type" AS ENUM('reference', 'custom');
  CREATE TYPE "public"."enum_pages_blocks_blog5_featured_blog_post_type" AS ENUM('reference', 'custom');
  CREATE TYPE "public"."enum_pages_blocks_blog5_font_family" AS ENUM('default', 'Arial, sans-serif', '"Times New Roman", serif', 'Georgia, serif', 'Verdana, sans-serif', 'Helvetica, Arial, sans-serif', '"Courier New", monospace', '"Roboto", sans-serif', '"Open Sans", sans-serif', '"Lato", sans-serif', '"Montserrat", sans-serif', '"Playfair Display", serif', '"Inter", sans-serif', '"Poppins", sans-serif', '"Raleway", sans-serif');
  CREATE TYPE "public"."enum_pages_blocks_blog7_tabs_content_type" AS ENUM('reference', 'custom');
  CREATE TYPE "public"."enum_pages_blocks_blog7_featured_blog_post_type" AS ENUM('reference', 'custom');
  CREATE TYPE "public"."enum_pages_blocks_blog7_font_family" AS ENUM('default', 'Arial, sans-serif', '"Times New Roman", serif', 'Georgia, serif', 'Verdana, sans-serif', 'Helvetica, Arial, sans-serif', '"Courier New", monospace', '"Roboto", sans-serif', '"Open Sans", sans-serif', '"Lato", sans-serif', '"Montserrat", sans-serif', '"Playfair Display", serif', '"Inter", sans-serif', '"Poppins", sans-serif', '"Raleway", sans-serif');
  CREATE TYPE "public"."enum_pages_blocks_blog9_small_featured_blog_posts_type" AS ENUM('reference', 'custom');
  CREATE TYPE "public"."enum_pages_blocks_blog9_blog_posts_type" AS ENUM('reference', 'custom');
  CREATE TYPE "public"."enum_pages_blocks_blog9_featured_blog_post_type" AS ENUM('reference', 'custom');
  CREATE TYPE "public"."enum_pages_blocks_blog9_font_family" AS ENUM('default', 'Arial, sans-serif', '"Times New Roman", serif', 'Georgia, serif', 'Verdana, sans-serif', 'Helvetica, Arial, sans-serif', '"Courier New", monospace', '"Roboto", sans-serif', '"Open Sans", sans-serif', '"Lato", sans-serif', '"Montserrat", sans-serif', '"Playfair Display", serif', '"Inter", sans-serif', '"Poppins", sans-serif', '"Raleway", sans-serif');
  CREATE TYPE "public"."enum__pages_v_blocks_banner9_social_media_links_type" AS ENUM('reference', 'custom');
  CREATE TYPE "public"."enum__pages_v_blocks_banner9_font_family" AS ENUM('default', 'Arial, sans-serif', '"Times New Roman", serif', 'Georgia, serif', 'Verdana, sans-serif', 'Helvetica, Arial, sans-serif', '"Courier New", monospace', '"Roboto", sans-serif', '"Open Sans", sans-serif', '"Lato", sans-serif', '"Montserrat", sans-serif', '"Playfair Display", serif', '"Inter", sans-serif', '"Poppins", sans-serif', '"Raleway", sans-serif');
  CREATE TYPE "public"."enum__pages_v_blocks_blog1_tabs_content_type" AS ENUM('reference', 'custom');
  CREATE TYPE "public"."enum__pages_v_blocks_blog1_font_family" AS ENUM('default', 'Arial, sans-serif', '"Times New Roman", serif', 'Georgia, serif', 'Verdana, sans-serif', 'Helvetica, Arial, sans-serif', '"Courier New", monospace', '"Roboto", sans-serif', '"Open Sans", sans-serif', '"Lato", sans-serif', '"Montserrat", sans-serif', '"Playfair Display", serif', '"Inter", sans-serif', '"Poppins", sans-serif', '"Raleway", sans-serif');
  CREATE TYPE "public"."enum__pages_v_blocks_blog5_tabs_content_type" AS ENUM('reference', 'custom');
  CREATE TYPE "public"."enum__pages_v_blocks_blog5_featured_blog_post_type" AS ENUM('reference', 'custom');
  CREATE TYPE "public"."enum__pages_v_blocks_blog5_font_family" AS ENUM('default', 'Arial, sans-serif', '"Times New Roman", serif', 'Georgia, serif', 'Verdana, sans-serif', 'Helvetica, Arial, sans-serif', '"Courier New", monospace', '"Roboto", sans-serif', '"Open Sans", sans-serif', '"Lato", sans-serif', '"Montserrat", sans-serif', '"Playfair Display", serif', '"Inter", sans-serif', '"Poppins", sans-serif', '"Raleway", sans-serif');
  CREATE TYPE "public"."enum__pages_v_blocks_blog7_tabs_content_type" AS ENUM('reference', 'custom');
  CREATE TYPE "public"."enum__pages_v_blocks_blog7_featured_blog_post_type" AS ENUM('reference', 'custom');
  CREATE TYPE "public"."enum__pages_v_blocks_blog7_font_family" AS ENUM('default', 'Arial, sans-serif', '"Times New Roman", serif', 'Georgia, serif', 'Verdana, sans-serif', 'Helvetica, Arial, sans-serif', '"Courier New", monospace', '"Roboto", sans-serif', '"Open Sans", sans-serif', '"Lato", sans-serif', '"Montserrat", sans-serif', '"Playfair Display", serif', '"Inter", sans-serif', '"Poppins", sans-serif', '"Raleway", sans-serif');
  CREATE TYPE "public"."enum__pages_v_blocks_blog9_small_featured_blog_posts_type" AS ENUM('reference', 'custom');
  CREATE TYPE "public"."enum__pages_v_blocks_blog9_blog_posts_type" AS ENUM('reference', 'custom');
  CREATE TYPE "public"."enum__pages_v_blocks_blog9_featured_blog_post_type" AS ENUM('reference', 'custom');
  CREATE TYPE "public"."enum__pages_v_blocks_blog9_font_family" AS ENUM('default', 'Arial, sans-serif', '"Times New Roman", serif', 'Georgia, serif', 'Verdana, sans-serif', 'Helvetica, Arial, sans-serif', '"Courier New", monospace', '"Roboto", sans-serif', '"Open Sans", sans-serif', '"Lato", sans-serif', '"Montserrat", sans-serif', '"Playfair Display", serif', '"Inter", sans-serif', '"Poppins", sans-serif', '"Raleway", sans-serif');
  ALTER TABLE "pages_blocks_banner9_social_media_links" ALTER COLUMN "url" DROP DEFAULT;
  ALTER TABLE "_pages_v_blocks_banner9_social_media_links" ALTER COLUMN "url" DROP DEFAULT;
  ALTER TABLE "pages_blocks_banner9_social_media_links" ADD COLUMN "type" "enum_pages_blocks_banner9_social_media_links_type" DEFAULT 'reference';
  ALTER TABLE "pages_blocks_banner9_social_media_links" ADD COLUMN "new_tab" boolean;
  ALTER TABLE "pages_blocks_banner9" ADD COLUMN "content" jsonb;
  ALTER TABLE "pages_blocks_banner9" ADD COLUMN "background_color" varchar;
  ALTER TABLE "pages_blocks_banner9" ADD COLUMN "text_color" varchar;
  ALTER TABLE "pages_blocks_banner9" ADD COLUMN "bold_text_color" varchar;
  ALTER TABLE "pages_blocks_banner9" ADD COLUMN "font_family" "enum_pages_blocks_banner9_font_family" DEFAULT 'default';
  ALTER TABLE "pages_blocks_banner9" ADD COLUMN "use_custom_font" boolean DEFAULT false;
  ALTER TABLE "pages_blocks_banner9" ADD COLUMN "custom_font_file_id" integer;
  ALTER TABLE "pages_blocks_banner9" ADD COLUMN "custom_font_name" varchar;
  ALTER TABLE "pages_blocks_blog1_tabs_content" ADD COLUMN "type" "enum_pages_blocks_blog1_tabs_content_type" DEFAULT 'reference';
  ALTER TABLE "pages_blocks_blog1_tabs_content" ADD COLUMN "new_tab" boolean;
  ALTER TABLE "pages_blocks_blog1_tabs_content" ADD COLUMN "post_content" jsonb;
  ALTER TABLE "pages_blocks_blog1" ADD COLUMN "content" jsonb;
  ALTER TABLE "pages_blocks_blog1" ADD COLUMN "background_color" varchar;
  ALTER TABLE "pages_blocks_blog1" ADD COLUMN "text_color" varchar;
  ALTER TABLE "pages_blocks_blog1" ADD COLUMN "bold_text_color" varchar;
  ALTER TABLE "pages_blocks_blog1" ADD COLUMN "font_family" "enum_pages_blocks_blog1_font_family" DEFAULT 'default';
  ALTER TABLE "pages_blocks_blog1" ADD COLUMN "use_custom_font" boolean DEFAULT false;
  ALTER TABLE "pages_blocks_blog1" ADD COLUMN "custom_font_file_id" integer;
  ALTER TABLE "pages_blocks_blog1" ADD COLUMN "custom_font_name" varchar;
  ALTER TABLE "pages_blocks_blog5_tabs_content" ADD COLUMN "type" "enum_pages_blocks_blog5_tabs_content_type" DEFAULT 'reference';
  ALTER TABLE "pages_blocks_blog5_tabs_content" ADD COLUMN "new_tab" boolean;
  ALTER TABLE "pages_blocks_blog5_tabs_content" ADD COLUMN "post_content" jsonb;
  ALTER TABLE "pages_blocks_blog5" ADD COLUMN "content" jsonb;
  ALTER TABLE "pages_blocks_blog5" ADD COLUMN "featured_blog_post_type" "enum_pages_blocks_blog5_featured_blog_post_type" DEFAULT 'reference';
  ALTER TABLE "pages_blocks_blog5" ADD COLUMN "featured_blog_post_new_tab" boolean;
  ALTER TABLE "pages_blocks_blog5" ADD COLUMN "featured_blog_post_post_content" jsonb;
  ALTER TABLE "pages_blocks_blog5" ADD COLUMN "background_color" varchar;
  ALTER TABLE "pages_blocks_blog5" ADD COLUMN "text_color" varchar;
  ALTER TABLE "pages_blocks_blog5" ADD COLUMN "bold_text_color" varchar;
  ALTER TABLE "pages_blocks_blog5" ADD COLUMN "font_family" "enum_pages_blocks_blog5_font_family" DEFAULT 'default';
  ALTER TABLE "pages_blocks_blog5" ADD COLUMN "use_custom_font" boolean DEFAULT false;
  ALTER TABLE "pages_blocks_blog5" ADD COLUMN "custom_font_file_id" integer;
  ALTER TABLE "pages_blocks_blog5" ADD COLUMN "custom_font_name" varchar;
  ALTER TABLE "pages_blocks_blog7_tabs_content" ADD COLUMN "type" "enum_pages_blocks_blog7_tabs_content_type" DEFAULT 'reference';
  ALTER TABLE "pages_blocks_blog7_tabs_content" ADD COLUMN "new_tab" boolean;
  ALTER TABLE "pages_blocks_blog7_tabs_content" ADD COLUMN "post_content" jsonb;
  ALTER TABLE "pages_blocks_blog7" ADD COLUMN "content" jsonb;
  ALTER TABLE "pages_blocks_blog7" ADD COLUMN "featured_blog_post_type" "enum_pages_blocks_blog7_featured_blog_post_type" DEFAULT 'reference';
  ALTER TABLE "pages_blocks_blog7" ADD COLUMN "featured_blog_post_new_tab" boolean;
  ALTER TABLE "pages_blocks_blog7" ADD COLUMN "featured_blog_post_post_content" jsonb;
  ALTER TABLE "pages_blocks_blog7" ADD COLUMN "background_color" varchar;
  ALTER TABLE "pages_blocks_blog7" ADD COLUMN "text_color" varchar;
  ALTER TABLE "pages_blocks_blog7" ADD COLUMN "bold_text_color" varchar;
  ALTER TABLE "pages_blocks_blog7" ADD COLUMN "font_family" "enum_pages_blocks_blog7_font_family" DEFAULT 'default';
  ALTER TABLE "pages_blocks_blog7" ADD COLUMN "use_custom_font" boolean DEFAULT false;
  ALTER TABLE "pages_blocks_blog7" ADD COLUMN "custom_font_file_id" integer;
  ALTER TABLE "pages_blocks_blog7" ADD COLUMN "custom_font_name" varchar;
  ALTER TABLE "pages_blocks_blog9_small_featured_blog_posts" ADD COLUMN "type" "enum_pages_blocks_blog9_small_featured_blog_posts_type" DEFAULT 'reference';
  ALTER TABLE "pages_blocks_blog9_small_featured_blog_posts" ADD COLUMN "new_tab" boolean;
  ALTER TABLE "pages_blocks_blog9_small_featured_blog_posts" ADD COLUMN "post_content" jsonb;
  ALTER TABLE "pages_blocks_blog9_blog_posts" ADD COLUMN "type" "enum_pages_blocks_blog9_blog_posts_type" DEFAULT 'reference';
  ALTER TABLE "pages_blocks_blog9_blog_posts" ADD COLUMN "new_tab" boolean;
  ALTER TABLE "pages_blocks_blog9_blog_posts" ADD COLUMN "post_content" jsonb;
  ALTER TABLE "pages_blocks_blog9" ADD COLUMN "content" jsonb;
  ALTER TABLE "pages_blocks_blog9" ADD COLUMN "featured_blog_post_type" "enum_pages_blocks_blog9_featured_blog_post_type" DEFAULT 'reference';
  ALTER TABLE "pages_blocks_blog9" ADD COLUMN "featured_blog_post_new_tab" boolean;
  ALTER TABLE "pages_blocks_blog9" ADD COLUMN "featured_blog_post_post_content" jsonb;
  ALTER TABLE "pages_blocks_blog9" ADD COLUMN "background_color" varchar;
  ALTER TABLE "pages_blocks_blog9" ADD COLUMN "text_color" varchar;
  ALTER TABLE "pages_blocks_blog9" ADD COLUMN "bold_text_color" varchar;
  ALTER TABLE "pages_blocks_blog9" ADD COLUMN "font_family" "enum_pages_blocks_blog9_font_family" DEFAULT 'default';
  ALTER TABLE "pages_blocks_blog9" ADD COLUMN "use_custom_font" boolean DEFAULT false;
  ALTER TABLE "pages_blocks_blog9" ADD COLUMN "custom_font_file_id" integer;
  ALTER TABLE "pages_blocks_blog9" ADD COLUMN "custom_font_name" varchar;
  ALTER TABLE "_pages_v_blocks_banner9_social_media_links" ADD COLUMN "type" "enum__pages_v_blocks_banner9_social_media_links_type" DEFAULT 'reference';
  ALTER TABLE "_pages_v_blocks_banner9_social_media_links" ADD COLUMN "new_tab" boolean;
  ALTER TABLE "_pages_v_blocks_banner9" ADD COLUMN "content" jsonb;
  ALTER TABLE "_pages_v_blocks_banner9" ADD COLUMN "background_color" varchar;
  ALTER TABLE "_pages_v_blocks_banner9" ADD COLUMN "text_color" varchar;
  ALTER TABLE "_pages_v_blocks_banner9" ADD COLUMN "bold_text_color" varchar;
  ALTER TABLE "_pages_v_blocks_banner9" ADD COLUMN "font_family" "enum__pages_v_blocks_banner9_font_family" DEFAULT 'default';
  ALTER TABLE "_pages_v_blocks_banner9" ADD COLUMN "use_custom_font" boolean DEFAULT false;
  ALTER TABLE "_pages_v_blocks_banner9" ADD COLUMN "custom_font_file_id" integer;
  ALTER TABLE "_pages_v_blocks_banner9" ADD COLUMN "custom_font_name" varchar;
  ALTER TABLE "_pages_v_blocks_blog1_tabs_content" ADD COLUMN "type" "enum__pages_v_blocks_blog1_tabs_content_type" DEFAULT 'reference';
  ALTER TABLE "_pages_v_blocks_blog1_tabs_content" ADD COLUMN "new_tab" boolean;
  ALTER TABLE "_pages_v_blocks_blog1_tabs_content" ADD COLUMN "post_content" jsonb;
  ALTER TABLE "_pages_v_blocks_blog1" ADD COLUMN "content" jsonb;
  ALTER TABLE "_pages_v_blocks_blog1" ADD COLUMN "background_color" varchar;
  ALTER TABLE "_pages_v_blocks_blog1" ADD COLUMN "text_color" varchar;
  ALTER TABLE "_pages_v_blocks_blog1" ADD COLUMN "bold_text_color" varchar;
  ALTER TABLE "_pages_v_blocks_blog1" ADD COLUMN "font_family" "enum__pages_v_blocks_blog1_font_family" DEFAULT 'default';
  ALTER TABLE "_pages_v_blocks_blog1" ADD COLUMN "use_custom_font" boolean DEFAULT false;
  ALTER TABLE "_pages_v_blocks_blog1" ADD COLUMN "custom_font_file_id" integer;
  ALTER TABLE "_pages_v_blocks_blog1" ADD COLUMN "custom_font_name" varchar;
  ALTER TABLE "_pages_v_blocks_blog5_tabs_content" ADD COLUMN "type" "enum__pages_v_blocks_blog5_tabs_content_type" DEFAULT 'reference';
  ALTER TABLE "_pages_v_blocks_blog5_tabs_content" ADD COLUMN "new_tab" boolean;
  ALTER TABLE "_pages_v_blocks_blog5_tabs_content" ADD COLUMN "post_content" jsonb;
  ALTER TABLE "_pages_v_blocks_blog5" ADD COLUMN "content" jsonb;
  ALTER TABLE "_pages_v_blocks_blog5" ADD COLUMN "featured_blog_post_type" "enum__pages_v_blocks_blog5_featured_blog_post_type" DEFAULT 'reference';
  ALTER TABLE "_pages_v_blocks_blog5" ADD COLUMN "featured_blog_post_new_tab" boolean;
  ALTER TABLE "_pages_v_blocks_blog5" ADD COLUMN "featured_blog_post_post_content" jsonb;
  ALTER TABLE "_pages_v_blocks_blog5" ADD COLUMN "background_color" varchar;
  ALTER TABLE "_pages_v_blocks_blog5" ADD COLUMN "text_color" varchar;
  ALTER TABLE "_pages_v_blocks_blog5" ADD COLUMN "bold_text_color" varchar;
  ALTER TABLE "_pages_v_blocks_blog5" ADD COLUMN "font_family" "enum__pages_v_blocks_blog5_font_family" DEFAULT 'default';
  ALTER TABLE "_pages_v_blocks_blog5" ADD COLUMN "use_custom_font" boolean DEFAULT false;
  ALTER TABLE "_pages_v_blocks_blog5" ADD COLUMN "custom_font_file_id" integer;
  ALTER TABLE "_pages_v_blocks_blog5" ADD COLUMN "custom_font_name" varchar;
  ALTER TABLE "_pages_v_blocks_blog7_tabs_content" ADD COLUMN "type" "enum__pages_v_blocks_blog7_tabs_content_type" DEFAULT 'reference';
  ALTER TABLE "_pages_v_blocks_blog7_tabs_content" ADD COLUMN "new_tab" boolean;
  ALTER TABLE "_pages_v_blocks_blog7_tabs_content" ADD COLUMN "post_content" jsonb;
  ALTER TABLE "_pages_v_blocks_blog7" ADD COLUMN "content" jsonb;
  ALTER TABLE "_pages_v_blocks_blog7" ADD COLUMN "featured_blog_post_type" "enum__pages_v_blocks_blog7_featured_blog_post_type" DEFAULT 'reference';
  ALTER TABLE "_pages_v_blocks_blog7" ADD COLUMN "featured_blog_post_new_tab" boolean;
  ALTER TABLE "_pages_v_blocks_blog7" ADD COLUMN "featured_blog_post_post_content" jsonb;
  ALTER TABLE "_pages_v_blocks_blog7" ADD COLUMN "background_color" varchar;
  ALTER TABLE "_pages_v_blocks_blog7" ADD COLUMN "text_color" varchar;
  ALTER TABLE "_pages_v_blocks_blog7" ADD COLUMN "bold_text_color" varchar;
  ALTER TABLE "_pages_v_blocks_blog7" ADD COLUMN "font_family" "enum__pages_v_blocks_blog7_font_family" DEFAULT 'default';
  ALTER TABLE "_pages_v_blocks_blog7" ADD COLUMN "use_custom_font" boolean DEFAULT false;
  ALTER TABLE "_pages_v_blocks_blog7" ADD COLUMN "custom_font_file_id" integer;
  ALTER TABLE "_pages_v_blocks_blog7" ADD COLUMN "custom_font_name" varchar;
  ALTER TABLE "_pages_v_blocks_blog9_small_featured_blog_posts" ADD COLUMN "type" "enum__pages_v_blocks_blog9_small_featured_blog_posts_type" DEFAULT 'reference';
  ALTER TABLE "_pages_v_blocks_blog9_small_featured_blog_posts" ADD COLUMN "new_tab" boolean;
  ALTER TABLE "_pages_v_blocks_blog9_small_featured_blog_posts" ADD COLUMN "post_content" jsonb;
  ALTER TABLE "_pages_v_blocks_blog9_blog_posts" ADD COLUMN "type" "enum__pages_v_blocks_blog9_blog_posts_type" DEFAULT 'reference';
  ALTER TABLE "_pages_v_blocks_blog9_blog_posts" ADD COLUMN "new_tab" boolean;
  ALTER TABLE "_pages_v_blocks_blog9_blog_posts" ADD COLUMN "post_content" jsonb;
  ALTER TABLE "_pages_v_blocks_blog9" ADD COLUMN "content" jsonb;
  ALTER TABLE "_pages_v_blocks_blog9" ADD COLUMN "featured_blog_post_type" "enum__pages_v_blocks_blog9_featured_blog_post_type" DEFAULT 'reference';
  ALTER TABLE "_pages_v_blocks_blog9" ADD COLUMN "featured_blog_post_new_tab" boolean;
  ALTER TABLE "_pages_v_blocks_blog9" ADD COLUMN "featured_blog_post_post_content" jsonb;
  ALTER TABLE "_pages_v_blocks_blog9" ADD COLUMN "background_color" varchar;
  ALTER TABLE "_pages_v_blocks_blog9" ADD COLUMN "text_color" varchar;
  ALTER TABLE "_pages_v_blocks_blog9" ADD COLUMN "bold_text_color" varchar;
  ALTER TABLE "_pages_v_blocks_blog9" ADD COLUMN "font_family" "enum__pages_v_blocks_blog9_font_family" DEFAULT 'default';
  ALTER TABLE "_pages_v_blocks_blog9" ADD COLUMN "use_custom_font" boolean DEFAULT false;
  ALTER TABLE "_pages_v_blocks_blog9" ADD COLUMN "custom_font_file_id" integer;
  ALTER TABLE "_pages_v_blocks_blog9" ADD COLUMN "custom_font_name" varchar;
  ALTER TABLE "pages_blocks_banner9" ADD CONSTRAINT "pages_blocks_banner9_custom_font_file_id_fonts_id_fk" FOREIGN KEY ("custom_font_file_id") REFERENCES "public"."fonts"("id") ON DELETE set null ON UPDATE no action;
  ALTER TABLE "pages_blocks_blog1" ADD CONSTRAINT "pages_blocks_blog1_custom_font_file_id_fonts_id_fk" FOREIGN KEY ("custom_font_file_id") REFERENCES "public"."fonts"("id") ON DELETE set null ON UPDATE no action;
  ALTER TABLE "pages_blocks_blog5" ADD CONSTRAINT "pages_blocks_blog5_custom_font_file_id_fonts_id_fk" FOREIGN KEY ("custom_font_file_id") REFERENCES "public"."fonts"("id") ON DELETE set null ON UPDATE no action;
  ALTER TABLE "pages_blocks_blog7" ADD CONSTRAINT "pages_blocks_blog7_custom_font_file_id_fonts_id_fk" FOREIGN KEY ("custom_font_file_id") REFERENCES "public"."fonts"("id") ON DELETE set null ON UPDATE no action;
  ALTER TABLE "pages_blocks_blog9" ADD CONSTRAINT "pages_blocks_blog9_custom_font_file_id_fonts_id_fk" FOREIGN KEY ("custom_font_file_id") REFERENCES "public"."fonts"("id") ON DELETE set null ON UPDATE no action;
  ALTER TABLE "_pages_v_blocks_banner9" ADD CONSTRAINT "_pages_v_blocks_banner9_custom_font_file_id_fonts_id_fk" FOREIGN KEY ("custom_font_file_id") REFERENCES "public"."fonts"("id") ON DELETE set null ON UPDATE no action;
  ALTER TABLE "_pages_v_blocks_blog1" ADD CONSTRAINT "_pages_v_blocks_blog1_custom_font_file_id_fonts_id_fk" FOREIGN KEY ("custom_font_file_id") REFERENCES "public"."fonts"("id") ON DELETE set null ON UPDATE no action;
  ALTER TABLE "_pages_v_blocks_blog5" ADD CONSTRAINT "_pages_v_blocks_blog5_custom_font_file_id_fonts_id_fk" FOREIGN KEY ("custom_font_file_id") REFERENCES "public"."fonts"("id") ON DELETE set null ON UPDATE no action;
  ALTER TABLE "_pages_v_blocks_blog7" ADD CONSTRAINT "_pages_v_blocks_blog7_custom_font_file_id_fonts_id_fk" FOREIGN KEY ("custom_font_file_id") REFERENCES "public"."fonts"("id") ON DELETE set null ON UPDATE no action;
  ALTER TABLE "_pages_v_blocks_blog9" ADD CONSTRAINT "_pages_v_blocks_blog9_custom_font_file_id_fonts_id_fk" FOREIGN KEY ("custom_font_file_id") REFERENCES "public"."fonts"("id") ON DELETE set null ON UPDATE no action;
  CREATE INDEX "pages_blocks_banner9_custom_font_file_idx" ON "pages_blocks_banner9" USING btree ("custom_font_file_id");
  CREATE INDEX "pages_blocks_blog1_custom_font_file_idx" ON "pages_blocks_blog1" USING btree ("custom_font_file_id");
  CREATE INDEX "pages_blocks_blog5_custom_font_file_idx" ON "pages_blocks_blog5" USING btree ("custom_font_file_id");
  CREATE INDEX "pages_blocks_blog7_custom_font_file_idx" ON "pages_blocks_blog7" USING btree ("custom_font_file_id");
  CREATE INDEX "pages_blocks_blog9_custom_font_file_idx" ON "pages_blocks_blog9" USING btree ("custom_font_file_id");
  CREATE INDEX "_pages_v_blocks_banner9_custom_font_file_idx" ON "_pages_v_blocks_banner9" USING btree ("custom_font_file_id");
  CREATE INDEX "_pages_v_blocks_blog1_custom_font_file_idx" ON "_pages_v_blocks_blog1" USING btree ("custom_font_file_id");
  CREATE INDEX "_pages_v_blocks_blog5_custom_font_file_idx" ON "_pages_v_blocks_blog5" USING btree ("custom_font_file_id");
  CREATE INDEX "_pages_v_blocks_blog7_custom_font_file_idx" ON "_pages_v_blocks_blog7" USING btree ("custom_font_file_id");
  CREATE INDEX "_pages_v_blocks_blog9_custom_font_file_idx" ON "_pages_v_blocks_blog9" USING btree ("custom_font_file_id");
  ALTER TABLE "pages_blocks_banner9" DROP COLUMN "heading";
  ALTER TABLE "pages_blocks_banner9" DROP COLUMN "description";
  ALTER TABLE "pages_blocks_blog1_tabs_content" DROP COLUMN "title";
  ALTER TABLE "pages_blocks_blog1_tabs_content" DROP COLUMN "description";
  ALTER TABLE "pages_blocks_blog1" DROP COLUMN "heading";
  ALTER TABLE "pages_blocks_blog1" DROP COLUMN "description";
  ALTER TABLE "pages_blocks_blog1" DROP COLUMN "category_link";
  ALTER TABLE "pages_blocks_blog5_tabs_content" DROP COLUMN "title";
  ALTER TABLE "pages_blocks_blog5_tabs_content" DROP COLUMN "description";
  ALTER TABLE "pages_blocks_blog5" DROP COLUMN "heading";
  ALTER TABLE "pages_blocks_blog5" DROP COLUMN "description";
  ALTER TABLE "pages_blocks_blog5" DROP COLUMN "category_link";
  ALTER TABLE "pages_blocks_blog5" DROP COLUMN "featured_blog_post_title";
  ALTER TABLE "pages_blocks_blog5" DROP COLUMN "featured_blog_post_description";
  ALTER TABLE "pages_blocks_blog7_tabs_content" DROP COLUMN "title";
  ALTER TABLE "pages_blocks_blog7_tabs_content" DROP COLUMN "description";
  ALTER TABLE "pages_blocks_blog7" DROP COLUMN "heading";
  ALTER TABLE "pages_blocks_blog7" DROP COLUMN "description";
  ALTER TABLE "pages_blocks_blog7" DROP COLUMN "featured_blog_post_title";
  ALTER TABLE "pages_blocks_blog7" DROP COLUMN "featured_blog_post_description";
  ALTER TABLE "pages_blocks_blog9_small_featured_blog_posts" DROP COLUMN "title";
  ALTER TABLE "pages_blocks_blog9_blog_posts" DROP COLUMN "title";
  ALTER TABLE "pages_blocks_blog9_blog_posts" DROP COLUMN "description";
  ALTER TABLE "pages_blocks_blog9" DROP COLUMN "heading";
  ALTER TABLE "pages_blocks_blog9" DROP COLUMN "description";
  ALTER TABLE "pages_blocks_blog9" DROP COLUMN "featured_blog_post_title";
  ALTER TABLE "pages_blocks_blog9" DROP COLUMN "featured_blog_post_description";
  ALTER TABLE "_pages_v_blocks_banner9" DROP COLUMN "heading";
  ALTER TABLE "_pages_v_blocks_banner9" DROP COLUMN "description";
  ALTER TABLE "_pages_v_blocks_blog1_tabs_content" DROP COLUMN "title";
  ALTER TABLE "_pages_v_blocks_blog1_tabs_content" DROP COLUMN "description";
  ALTER TABLE "_pages_v_blocks_blog1" DROP COLUMN "heading";
  ALTER TABLE "_pages_v_blocks_blog1" DROP COLUMN "description";
  ALTER TABLE "_pages_v_blocks_blog1" DROP COLUMN "category_link";
  ALTER TABLE "_pages_v_blocks_blog5_tabs_content" DROP COLUMN "title";
  ALTER TABLE "_pages_v_blocks_blog5_tabs_content" DROP COLUMN "description";
  ALTER TABLE "_pages_v_blocks_blog5" DROP COLUMN "heading";
  ALTER TABLE "_pages_v_blocks_blog5" DROP COLUMN "description";
  ALTER TABLE "_pages_v_blocks_blog5" DROP COLUMN "category_link";
  ALTER TABLE "_pages_v_blocks_blog5" DROP COLUMN "featured_blog_post_title";
  ALTER TABLE "_pages_v_blocks_blog5" DROP COLUMN "featured_blog_post_description";
  ALTER TABLE "_pages_v_blocks_blog7_tabs_content" DROP COLUMN "title";
  ALTER TABLE "_pages_v_blocks_blog7_tabs_content" DROP COLUMN "description";
  ALTER TABLE "_pages_v_blocks_blog7" DROP COLUMN "heading";
  ALTER TABLE "_pages_v_blocks_blog7" DROP COLUMN "description";
  ALTER TABLE "_pages_v_blocks_blog7" DROP COLUMN "featured_blog_post_title";
  ALTER TABLE "_pages_v_blocks_blog7" DROP COLUMN "featured_blog_post_description";
  ALTER TABLE "_pages_v_blocks_blog9_small_featured_blog_posts" DROP COLUMN "title";
  ALTER TABLE "_pages_v_blocks_blog9_blog_posts" DROP COLUMN "title";
  ALTER TABLE "_pages_v_blocks_blog9_blog_posts" DROP COLUMN "description";
  ALTER TABLE "_pages_v_blocks_blog9" DROP COLUMN "heading";
  ALTER TABLE "_pages_v_blocks_blog9" DROP COLUMN "description";
  ALTER TABLE "_pages_v_blocks_blog9" DROP COLUMN "featured_blog_post_title";
  ALTER TABLE "_pages_v_blocks_blog9" DROP COLUMN "featured_blog_post_description";`)
}

export async function down({ db, payload, req }: MigrateDownArgs): Promise<void> {
  await db.execute(sql`
   ALTER TABLE "pages_blocks_banner9" DROP CONSTRAINT "pages_blocks_banner9_custom_font_file_id_fonts_id_fk";
  
  ALTER TABLE "pages_blocks_blog1" DROP CONSTRAINT "pages_blocks_blog1_custom_font_file_id_fonts_id_fk";
  
  ALTER TABLE "pages_blocks_blog5" DROP CONSTRAINT "pages_blocks_blog5_custom_font_file_id_fonts_id_fk";
  
  ALTER TABLE "pages_blocks_blog7" DROP CONSTRAINT "pages_blocks_blog7_custom_font_file_id_fonts_id_fk";
  
  ALTER TABLE "pages_blocks_blog9" DROP CONSTRAINT "pages_blocks_blog9_custom_font_file_id_fonts_id_fk";
  
  ALTER TABLE "_pages_v_blocks_banner9" DROP CONSTRAINT "_pages_v_blocks_banner9_custom_font_file_id_fonts_id_fk";
  
  ALTER TABLE "_pages_v_blocks_blog1" DROP CONSTRAINT "_pages_v_blocks_blog1_custom_font_file_id_fonts_id_fk";
  
  ALTER TABLE "_pages_v_blocks_blog5" DROP CONSTRAINT "_pages_v_blocks_blog5_custom_font_file_id_fonts_id_fk";
  
  ALTER TABLE "_pages_v_blocks_blog7" DROP CONSTRAINT "_pages_v_blocks_blog7_custom_font_file_id_fonts_id_fk";
  
  ALTER TABLE "_pages_v_blocks_blog9" DROP CONSTRAINT "_pages_v_blocks_blog9_custom_font_file_id_fonts_id_fk";
  
  DROP INDEX "pages_blocks_banner9_custom_font_file_idx";
  DROP INDEX "pages_blocks_blog1_custom_font_file_idx";
  DROP INDEX "pages_blocks_blog5_custom_font_file_idx";
  DROP INDEX "pages_blocks_blog7_custom_font_file_idx";
  DROP INDEX "pages_blocks_blog9_custom_font_file_idx";
  DROP INDEX "_pages_v_blocks_banner9_custom_font_file_idx";
  DROP INDEX "_pages_v_blocks_blog1_custom_font_file_idx";
  DROP INDEX "_pages_v_blocks_blog5_custom_font_file_idx";
  DROP INDEX "_pages_v_blocks_blog7_custom_font_file_idx";
  DROP INDEX "_pages_v_blocks_blog9_custom_font_file_idx";
  ALTER TABLE "pages_blocks_banner9_social_media_links" ALTER COLUMN "url" SET DEFAULT '#';
  ALTER TABLE "_pages_v_blocks_banner9_social_media_links" ALTER COLUMN "url" SET DEFAULT '#';
  ALTER TABLE "pages_blocks_banner9" ADD COLUMN "heading" varchar DEFAULT 'Medium length banner heading goes here';
  ALTER TABLE "pages_blocks_banner9" ADD COLUMN "description" varchar DEFAULT 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.';
  ALTER TABLE "pages_blocks_blog1_tabs_content" ADD COLUMN "title" varchar;
  ALTER TABLE "pages_blocks_blog1_tabs_content" ADD COLUMN "description" varchar;
  ALTER TABLE "pages_blocks_blog1" ADD COLUMN "heading" varchar DEFAULT 'Short heading goes here';
  ALTER TABLE "pages_blocks_blog1" ADD COLUMN "description" varchar DEFAULT 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.';
  ALTER TABLE "pages_blocks_blog1" ADD COLUMN "category_link" varchar DEFAULT '#';
  ALTER TABLE "pages_blocks_blog5_tabs_content" ADD COLUMN "title" varchar;
  ALTER TABLE "pages_blocks_blog5_tabs_content" ADD COLUMN "description" varchar;
  ALTER TABLE "pages_blocks_blog5" ADD COLUMN "heading" varchar DEFAULT 'Short heading goes here';
  ALTER TABLE "pages_blocks_blog5" ADD COLUMN "description" varchar DEFAULT 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.';
  ALTER TABLE "pages_blocks_blog5" ADD COLUMN "category_link" varchar DEFAULT '#';
  ALTER TABLE "pages_blocks_blog5" ADD COLUMN "featured_blog_post_title" varchar;
  ALTER TABLE "pages_blocks_blog5" ADD COLUMN "featured_blog_post_description" varchar;
  ALTER TABLE "pages_blocks_blog7_tabs_content" ADD COLUMN "title" varchar;
  ALTER TABLE "pages_blocks_blog7_tabs_content" ADD COLUMN "description" varchar;
  ALTER TABLE "pages_blocks_blog7" ADD COLUMN "heading" varchar DEFAULT 'Short heading goes here';
  ALTER TABLE "pages_blocks_blog7" ADD COLUMN "description" varchar DEFAULT 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.';
  ALTER TABLE "pages_blocks_blog7" ADD COLUMN "featured_blog_post_title" varchar;
  ALTER TABLE "pages_blocks_blog7" ADD COLUMN "featured_blog_post_description" varchar;
  ALTER TABLE "pages_blocks_blog9_small_featured_blog_posts" ADD COLUMN "title" varchar;
  ALTER TABLE "pages_blocks_blog9_blog_posts" ADD COLUMN "title" varchar;
  ALTER TABLE "pages_blocks_blog9_blog_posts" ADD COLUMN "description" varchar;
  ALTER TABLE "pages_blocks_blog9" ADD COLUMN "heading" varchar DEFAULT 'Short heading goes here';
  ALTER TABLE "pages_blocks_blog9" ADD COLUMN "description" varchar DEFAULT 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.';
  ALTER TABLE "pages_blocks_blog9" ADD COLUMN "featured_blog_post_title" varchar;
  ALTER TABLE "pages_blocks_blog9" ADD COLUMN "featured_blog_post_description" varchar;
  ALTER TABLE "_pages_v_blocks_banner9" ADD COLUMN "heading" varchar DEFAULT 'Medium length banner heading goes here';
  ALTER TABLE "_pages_v_blocks_banner9" ADD COLUMN "description" varchar DEFAULT 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.';
  ALTER TABLE "_pages_v_blocks_blog1_tabs_content" ADD COLUMN "title" varchar;
  ALTER TABLE "_pages_v_blocks_blog1_tabs_content" ADD COLUMN "description" varchar;
  ALTER TABLE "_pages_v_blocks_blog1" ADD COLUMN "heading" varchar DEFAULT 'Short heading goes here';
  ALTER TABLE "_pages_v_blocks_blog1" ADD COLUMN "description" varchar DEFAULT 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.';
  ALTER TABLE "_pages_v_blocks_blog1" ADD COLUMN "category_link" varchar DEFAULT '#';
  ALTER TABLE "_pages_v_blocks_blog5_tabs_content" ADD COLUMN "title" varchar;
  ALTER TABLE "_pages_v_blocks_blog5_tabs_content" ADD COLUMN "description" varchar;
  ALTER TABLE "_pages_v_blocks_blog5" ADD COLUMN "heading" varchar DEFAULT 'Short heading goes here';
  ALTER TABLE "_pages_v_blocks_blog5" ADD COLUMN "description" varchar DEFAULT 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.';
  ALTER TABLE "_pages_v_blocks_blog5" ADD COLUMN "category_link" varchar DEFAULT '#';
  ALTER TABLE "_pages_v_blocks_blog5" ADD COLUMN "featured_blog_post_title" varchar;
  ALTER TABLE "_pages_v_blocks_blog5" ADD COLUMN "featured_blog_post_description" varchar;
  ALTER TABLE "_pages_v_blocks_blog7_tabs_content" ADD COLUMN "title" varchar;
  ALTER TABLE "_pages_v_blocks_blog7_tabs_content" ADD COLUMN "description" varchar;
  ALTER TABLE "_pages_v_blocks_blog7" ADD COLUMN "heading" varchar DEFAULT 'Short heading goes here';
  ALTER TABLE "_pages_v_blocks_blog7" ADD COLUMN "description" varchar DEFAULT 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.';
  ALTER TABLE "_pages_v_blocks_blog7" ADD COLUMN "featured_blog_post_title" varchar;
  ALTER TABLE "_pages_v_blocks_blog7" ADD COLUMN "featured_blog_post_description" varchar;
  ALTER TABLE "_pages_v_blocks_blog9_small_featured_blog_posts" ADD COLUMN "title" varchar;
  ALTER TABLE "_pages_v_blocks_blog9_blog_posts" ADD COLUMN "title" varchar;
  ALTER TABLE "_pages_v_blocks_blog9_blog_posts" ADD COLUMN "description" varchar;
  ALTER TABLE "_pages_v_blocks_blog9" ADD COLUMN "heading" varchar DEFAULT 'Short heading goes here';
  ALTER TABLE "_pages_v_blocks_blog9" ADD COLUMN "description" varchar DEFAULT 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.';
  ALTER TABLE "_pages_v_blocks_blog9" ADD COLUMN "featured_blog_post_title" varchar;
  ALTER TABLE "_pages_v_blocks_blog9" ADD COLUMN "featured_blog_post_description" varchar;
  ALTER TABLE "pages_blocks_banner9_social_media_links" DROP COLUMN "type";
  ALTER TABLE "pages_blocks_banner9_social_media_links" DROP COLUMN "new_tab";
  ALTER TABLE "pages_blocks_banner9" DROP COLUMN "content";
  ALTER TABLE "pages_blocks_banner9" DROP COLUMN "background_color";
  ALTER TABLE "pages_blocks_banner9" DROP COLUMN "text_color";
  ALTER TABLE "pages_blocks_banner9" DROP COLUMN "bold_text_color";
  ALTER TABLE "pages_blocks_banner9" DROP COLUMN "font_family";
  ALTER TABLE "pages_blocks_banner9" DROP COLUMN "use_custom_font";
  ALTER TABLE "pages_blocks_banner9" DROP COLUMN "custom_font_file_id";
  ALTER TABLE "pages_blocks_banner9" DROP COLUMN "custom_font_name";
  ALTER TABLE "pages_blocks_blog1_tabs_content" DROP COLUMN "type";
  ALTER TABLE "pages_blocks_blog1_tabs_content" DROP COLUMN "new_tab";
  ALTER TABLE "pages_blocks_blog1_tabs_content" DROP COLUMN "post_content";
  ALTER TABLE "pages_blocks_blog1" DROP COLUMN "content";
  ALTER TABLE "pages_blocks_blog1" DROP COLUMN "background_color";
  ALTER TABLE "pages_blocks_blog1" DROP COLUMN "text_color";
  ALTER TABLE "pages_blocks_blog1" DROP COLUMN "bold_text_color";
  ALTER TABLE "pages_blocks_blog1" DROP COLUMN "font_family";
  ALTER TABLE "pages_blocks_blog1" DROP COLUMN "use_custom_font";
  ALTER TABLE "pages_blocks_blog1" DROP COLUMN "custom_font_file_id";
  ALTER TABLE "pages_blocks_blog1" DROP COLUMN "custom_font_name";
  ALTER TABLE "pages_blocks_blog5_tabs_content" DROP COLUMN "type";
  ALTER TABLE "pages_blocks_blog5_tabs_content" DROP COLUMN "new_tab";
  ALTER TABLE "pages_blocks_blog5_tabs_content" DROP COLUMN "post_content";
  ALTER TABLE "pages_blocks_blog5" DROP COLUMN "content";
  ALTER TABLE "pages_blocks_blog5" DROP COLUMN "featured_blog_post_type";
  ALTER TABLE "pages_blocks_blog5" DROP COLUMN "featured_blog_post_new_tab";
  ALTER TABLE "pages_blocks_blog5" DROP COLUMN "featured_blog_post_post_content";
  ALTER TABLE "pages_blocks_blog5" DROP COLUMN "background_color";
  ALTER TABLE "pages_blocks_blog5" DROP COLUMN "text_color";
  ALTER TABLE "pages_blocks_blog5" DROP COLUMN "bold_text_color";
  ALTER TABLE "pages_blocks_blog5" DROP COLUMN "font_family";
  ALTER TABLE "pages_blocks_blog5" DROP COLUMN "use_custom_font";
  ALTER TABLE "pages_blocks_blog5" DROP COLUMN "custom_font_file_id";
  ALTER TABLE "pages_blocks_blog5" DROP COLUMN "custom_font_name";
  ALTER TABLE "pages_blocks_blog7_tabs_content" DROP COLUMN "type";
  ALTER TABLE "pages_blocks_blog7_tabs_content" DROP COLUMN "new_tab";
  ALTER TABLE "pages_blocks_blog7_tabs_content" DROP COLUMN "post_content";
  ALTER TABLE "pages_blocks_blog7" DROP COLUMN "content";
  ALTER TABLE "pages_blocks_blog7" DROP COLUMN "featured_blog_post_type";
  ALTER TABLE "pages_blocks_blog7" DROP COLUMN "featured_blog_post_new_tab";
  ALTER TABLE "pages_blocks_blog7" DROP COLUMN "featured_blog_post_post_content";
  ALTER TABLE "pages_blocks_blog7" DROP COLUMN "background_color";
  ALTER TABLE "pages_blocks_blog7" DROP COLUMN "text_color";
  ALTER TABLE "pages_blocks_blog7" DROP COLUMN "bold_text_color";
  ALTER TABLE "pages_blocks_blog7" DROP COLUMN "font_family";
  ALTER TABLE "pages_blocks_blog7" DROP COLUMN "use_custom_font";
  ALTER TABLE "pages_blocks_blog7" DROP COLUMN "custom_font_file_id";
  ALTER TABLE "pages_blocks_blog7" DROP COLUMN "custom_font_name";
  ALTER TABLE "pages_blocks_blog9_small_featured_blog_posts" DROP COLUMN "type";
  ALTER TABLE "pages_blocks_blog9_small_featured_blog_posts" DROP COLUMN "new_tab";
  ALTER TABLE "pages_blocks_blog9_small_featured_blog_posts" DROP COLUMN "post_content";
  ALTER TABLE "pages_blocks_blog9_blog_posts" DROP COLUMN "type";
  ALTER TABLE "pages_blocks_blog9_blog_posts" DROP COLUMN "new_tab";
  ALTER TABLE "pages_blocks_blog9_blog_posts" DROP COLUMN "post_content";
  ALTER TABLE "pages_blocks_blog9" DROP COLUMN "content";
  ALTER TABLE "pages_blocks_blog9" DROP COLUMN "featured_blog_post_type";
  ALTER TABLE "pages_blocks_blog9" DROP COLUMN "featured_blog_post_new_tab";
  ALTER TABLE "pages_blocks_blog9" DROP COLUMN "featured_blog_post_post_content";
  ALTER TABLE "pages_blocks_blog9" DROP COLUMN "background_color";
  ALTER TABLE "pages_blocks_blog9" DROP COLUMN "text_color";
  ALTER TABLE "pages_blocks_blog9" DROP COLUMN "bold_text_color";
  ALTER TABLE "pages_blocks_blog9" DROP COLUMN "font_family";
  ALTER TABLE "pages_blocks_blog9" DROP COLUMN "use_custom_font";
  ALTER TABLE "pages_blocks_blog9" DROP COLUMN "custom_font_file_id";
  ALTER TABLE "pages_blocks_blog9" DROP COLUMN "custom_font_name";
  ALTER TABLE "_pages_v_blocks_banner9_social_media_links" DROP COLUMN "type";
  ALTER TABLE "_pages_v_blocks_banner9_social_media_links" DROP COLUMN "new_tab";
  ALTER TABLE "_pages_v_blocks_banner9" DROP COLUMN "content";
  ALTER TABLE "_pages_v_blocks_banner9" DROP COLUMN "background_color";
  ALTER TABLE "_pages_v_blocks_banner9" DROP COLUMN "text_color";
  ALTER TABLE "_pages_v_blocks_banner9" DROP COLUMN "bold_text_color";
  ALTER TABLE "_pages_v_blocks_banner9" DROP COLUMN "font_family";
  ALTER TABLE "_pages_v_blocks_banner9" DROP COLUMN "use_custom_font";
  ALTER TABLE "_pages_v_blocks_banner9" DROP COLUMN "custom_font_file_id";
  ALTER TABLE "_pages_v_blocks_banner9" DROP COLUMN "custom_font_name";
  ALTER TABLE "_pages_v_blocks_blog1_tabs_content" DROP COLUMN "type";
  ALTER TABLE "_pages_v_blocks_blog1_tabs_content" DROP COLUMN "new_tab";
  ALTER TABLE "_pages_v_blocks_blog1_tabs_content" DROP COLUMN "post_content";
  ALTER TABLE "_pages_v_blocks_blog1" DROP COLUMN "content";
  ALTER TABLE "_pages_v_blocks_blog1" DROP COLUMN "background_color";
  ALTER TABLE "_pages_v_blocks_blog1" DROP COLUMN "text_color";
  ALTER TABLE "_pages_v_blocks_blog1" DROP COLUMN "bold_text_color";
  ALTER TABLE "_pages_v_blocks_blog1" DROP COLUMN "font_family";
  ALTER TABLE "_pages_v_blocks_blog1" DROP COLUMN "use_custom_font";
  ALTER TABLE "_pages_v_blocks_blog1" DROP COLUMN "custom_font_file_id";
  ALTER TABLE "_pages_v_blocks_blog1" DROP COLUMN "custom_font_name";
  ALTER TABLE "_pages_v_blocks_blog5_tabs_content" DROP COLUMN "type";
  ALTER TABLE "_pages_v_blocks_blog5_tabs_content" DROP COLUMN "new_tab";
  ALTER TABLE "_pages_v_blocks_blog5_tabs_content" DROP COLUMN "post_content";
  ALTER TABLE "_pages_v_blocks_blog5" DROP COLUMN "content";
  ALTER TABLE "_pages_v_blocks_blog5" DROP COLUMN "featured_blog_post_type";
  ALTER TABLE "_pages_v_blocks_blog5" DROP COLUMN "featured_blog_post_new_tab";
  ALTER TABLE "_pages_v_blocks_blog5" DROP COLUMN "featured_blog_post_post_content";
  ALTER TABLE "_pages_v_blocks_blog5" DROP COLUMN "background_color";
  ALTER TABLE "_pages_v_blocks_blog5" DROP COLUMN "text_color";
  ALTER TABLE "_pages_v_blocks_blog5" DROP COLUMN "bold_text_color";
  ALTER TABLE "_pages_v_blocks_blog5" DROP COLUMN "font_family";
  ALTER TABLE "_pages_v_blocks_blog5" DROP COLUMN "use_custom_font";
  ALTER TABLE "_pages_v_blocks_blog5" DROP COLUMN "custom_font_file_id";
  ALTER TABLE "_pages_v_blocks_blog5" DROP COLUMN "custom_font_name";
  ALTER TABLE "_pages_v_blocks_blog7_tabs_content" DROP COLUMN "type";
  ALTER TABLE "_pages_v_blocks_blog7_tabs_content" DROP COLUMN "new_tab";
  ALTER TABLE "_pages_v_blocks_blog7_tabs_content" DROP COLUMN "post_content";
  ALTER TABLE "_pages_v_blocks_blog7" DROP COLUMN "content";
  ALTER TABLE "_pages_v_blocks_blog7" DROP COLUMN "featured_blog_post_type";
  ALTER TABLE "_pages_v_blocks_blog7" DROP COLUMN "featured_blog_post_new_tab";
  ALTER TABLE "_pages_v_blocks_blog7" DROP COLUMN "featured_blog_post_post_content";
  ALTER TABLE "_pages_v_blocks_blog7" DROP COLUMN "background_color";
  ALTER TABLE "_pages_v_blocks_blog7" DROP COLUMN "text_color";
  ALTER TABLE "_pages_v_blocks_blog7" DROP COLUMN "bold_text_color";
  ALTER TABLE "_pages_v_blocks_blog7" DROP COLUMN "font_family";
  ALTER TABLE "_pages_v_blocks_blog7" DROP COLUMN "use_custom_font";
  ALTER TABLE "_pages_v_blocks_blog7" DROP COLUMN "custom_font_file_id";
  ALTER TABLE "_pages_v_blocks_blog7" DROP COLUMN "custom_font_name";
  ALTER TABLE "_pages_v_blocks_blog9_small_featured_blog_posts" DROP COLUMN "type";
  ALTER TABLE "_pages_v_blocks_blog9_small_featured_blog_posts" DROP COLUMN "new_tab";
  ALTER TABLE "_pages_v_blocks_blog9_small_featured_blog_posts" DROP COLUMN "post_content";
  ALTER TABLE "_pages_v_blocks_blog9_blog_posts" DROP COLUMN "type";
  ALTER TABLE "_pages_v_blocks_blog9_blog_posts" DROP COLUMN "new_tab";
  ALTER TABLE "_pages_v_blocks_blog9_blog_posts" DROP COLUMN "post_content";
  ALTER TABLE "_pages_v_blocks_blog9" DROP COLUMN "content";
  ALTER TABLE "_pages_v_blocks_blog9" DROP COLUMN "featured_blog_post_type";
  ALTER TABLE "_pages_v_blocks_blog9" DROP COLUMN "featured_blog_post_new_tab";
  ALTER TABLE "_pages_v_blocks_blog9" DROP COLUMN "featured_blog_post_post_content";
  ALTER TABLE "_pages_v_blocks_blog9" DROP COLUMN "background_color";
  ALTER TABLE "_pages_v_blocks_blog9" DROP COLUMN "text_color";
  ALTER TABLE "_pages_v_blocks_blog9" DROP COLUMN "bold_text_color";
  ALTER TABLE "_pages_v_blocks_blog9" DROP COLUMN "font_family";
  ALTER TABLE "_pages_v_blocks_blog9" DROP COLUMN "use_custom_font";
  ALTER TABLE "_pages_v_blocks_blog9" DROP COLUMN "custom_font_file_id";
  ALTER TABLE "_pages_v_blocks_blog9" DROP COLUMN "custom_font_name";
  DROP TYPE "public"."enum_pages_blocks_banner9_social_media_links_type";
  DROP TYPE "public"."enum_pages_blocks_banner9_font_family";
  DROP TYPE "public"."enum_pages_blocks_blog1_tabs_content_type";
  DROP TYPE "public"."enum_pages_blocks_blog1_font_family";
  DROP TYPE "public"."enum_pages_blocks_blog5_tabs_content_type";
  DROP TYPE "public"."enum_pages_blocks_blog5_featured_blog_post_type";
  DROP TYPE "public"."enum_pages_blocks_blog5_font_family";
  DROP TYPE "public"."enum_pages_blocks_blog7_tabs_content_type";
  DROP TYPE "public"."enum_pages_blocks_blog7_featured_blog_post_type";
  DROP TYPE "public"."enum_pages_blocks_blog7_font_family";
  DROP TYPE "public"."enum_pages_blocks_blog9_small_featured_blog_posts_type";
  DROP TYPE "public"."enum_pages_blocks_blog9_blog_posts_type";
  DROP TYPE "public"."enum_pages_blocks_blog9_featured_blog_post_type";
  DROP TYPE "public"."enum_pages_blocks_blog9_font_family";
  DROP TYPE "public"."enum__pages_v_blocks_banner9_social_media_links_type";
  DROP TYPE "public"."enum__pages_v_blocks_banner9_font_family";
  DROP TYPE "public"."enum__pages_v_blocks_blog1_tabs_content_type";
  DROP TYPE "public"."enum__pages_v_blocks_blog1_font_family";
  DROP TYPE "public"."enum__pages_v_blocks_blog5_tabs_content_type";
  DROP TYPE "public"."enum__pages_v_blocks_blog5_featured_blog_post_type";
  DROP TYPE "public"."enum__pages_v_blocks_blog5_font_family";
  DROP TYPE "public"."enum__pages_v_blocks_blog7_tabs_content_type";
  DROP TYPE "public"."enum__pages_v_blocks_blog7_featured_blog_post_type";
  DROP TYPE "public"."enum__pages_v_blocks_blog7_font_family";
  DROP TYPE "public"."enum__pages_v_blocks_blog9_small_featured_blog_posts_type";
  DROP TYPE "public"."enum__pages_v_blocks_blog9_blog_posts_type";
  DROP TYPE "public"."enum__pages_v_blocks_blog9_featured_blog_post_type";
  DROP TYPE "public"."enum__pages_v_blocks_blog9_font_family";`)
}
