import { MigrateUpArgs, MigrateDownArgs, sql } from '@payloadcms/db-postgres'

export async function up({ db, payload, req }: MigrateUpArgs): Promise<void> {
  await db.execute(sql`
   CREATE TYPE "public"."enum_pages_blocks_layout_drop_header_style_font_family" AS ENUM('default', 'Arial, sans-serif', '"Times New Roman", serif', 'Georgia, serif', 'Verdana, sans-serif', 'Helvetica, Arial, sans-serif', '"Courier New", monospace', '"Roboto", sans-serif', '"Open Sans", sans-serif', '"Lato", sans-serif', '"Montserrat", sans-serif', '"Playfair Display", serif', '"Inter", sans-serif', '"Poppins", sans-serif', '"Raleway", sans-serif');
  CREATE TYPE "public"."enum_pages_blocks_layout_drop_elements_style_shadow" AS ENUM('none', 'sm', 'md', 'lg', 'xl');
  CREATE TYPE "public"."enum_pages_blocks_layout_drop_elements_style_font_family" AS ENUM('default', 'Arial, sans-serif', '"Times New Roman", serif', 'Georgia, serif', 'Verdana, sans-serif', 'Helvetica, Arial, sans-serif', '"Courier New", monospace', '"Roboto", sans-serif', '"Open Sans", sans-serif', '"Lato", sans-serif', '"Montserrat", sans-serif', '"Playfair Display", serif', '"Inter", sans-serif', '"Poppins", sans-serif', '"Raleway", sans-serif');
  CREATE TYPE "public"."enum_pages_blocks_layout_drop_contact_form_shadow" AS ENUM('none', 'sm', 'md', 'lg', 'xl');
  CREATE TYPE "public"."enum_pages_blocks_layout_drop_contact_form_font_family" AS ENUM('default', 'Arial, sans-serif', '"Times New Roman", serif', 'Georgia, serif', 'Verdana, sans-serif', 'Helvetica, Arial, sans-serif', '"Courier New", monospace', '"Roboto", sans-serif', '"Open Sans", sans-serif', '"Lato", sans-serif', '"Montserrat", sans-serif', '"Playfair Display", serif', '"Inter", sans-serif', '"Poppins", sans-serif', '"Raleway", sans-serif');
  CREATE TYPE "public"."enum_pages_blocks_layout_drop_privacy_policy_font_family" AS ENUM('default', 'Arial, sans-serif', '"Times New Roman", serif', 'Georgia, serif', 'Verdana, sans-serif', 'Helvetica, Arial, sans-serif', '"Courier New", monospace', '"Roboto", sans-serif', '"Open Sans", sans-serif', '"Lato", sans-serif', '"Montserrat", sans-serif', '"Playfair Display", serif', '"Inter", sans-serif', '"Poppins", sans-serif', '"Raleway", sans-serif');
  CREATE TYPE "public"."enum_pages_blocks_layout_drop_block_height_mode" AS ENUM('auto', 'viewport', 'custom');
  CREATE TYPE "public"."enum_pages_blocks_layout_drop_background_type" AS ENUM('color', 'image', 'video');
  CREATE TYPE "public"."enum_pages_blocks_layout_drop_background_color_mode" AS ENUM('solid', 'gradient');
  CREATE TYPE "public"."enum_pages_blocks_layout_drop_gradient_direction" AS ENUM('to-right', 'to-left', 'to-bottom', 'to-top', 'diagonal-down', 'diagonal-up');
  CREATE TYPE "public"."enum__pages_v_blocks_layout_drop_header_style_font_family" AS ENUM('default', 'Arial, sans-serif', '"Times New Roman", serif', 'Georgia, serif', 'Verdana, sans-serif', 'Helvetica, Arial, sans-serif', '"Courier New", monospace', '"Roboto", sans-serif', '"Open Sans", sans-serif', '"Lato", sans-serif', '"Montserrat", sans-serif', '"Playfair Display", serif', '"Inter", sans-serif', '"Poppins", sans-serif', '"Raleway", sans-serif');
  CREATE TYPE "public"."enum__pages_v_blocks_layout_drop_elements_style_shadow" AS ENUM('none', 'sm', 'md', 'lg', 'xl');
  CREATE TYPE "public"."enum__pages_v_blocks_layout_drop_elements_style_font_family" AS ENUM('default', 'Arial, sans-serif', '"Times New Roman", serif', 'Georgia, serif', 'Verdana, sans-serif', 'Helvetica, Arial, sans-serif', '"Courier New", monospace', '"Roboto", sans-serif', '"Open Sans", sans-serif', '"Lato", sans-serif', '"Montserrat", sans-serif', '"Playfair Display", serif', '"Inter", sans-serif', '"Poppins", sans-serif', '"Raleway", sans-serif');
  CREATE TYPE "public"."enum__pages_v_blocks_layout_drop_contact_form_shadow" AS ENUM('none', 'sm', 'md', 'lg', 'xl');
  CREATE TYPE "public"."enum__pages_v_blocks_layout_drop_contact_form_font_family" AS ENUM('default', 'Arial, sans-serif', '"Times New Roman", serif', 'Georgia, serif', 'Verdana, sans-serif', 'Helvetica, Arial, sans-serif', '"Courier New", monospace', '"Roboto", sans-serif', '"Open Sans", sans-serif', '"Lato", sans-serif', '"Montserrat", sans-serif', '"Playfair Display", serif', '"Inter", sans-serif', '"Poppins", sans-serif', '"Raleway", sans-serif');
  CREATE TYPE "public"."enum__pages_v_blocks_layout_drop_privacy_policy_font_family" AS ENUM('default', 'Arial, sans-serif', '"Times New Roman", serif', 'Georgia, serif', 'Verdana, sans-serif', 'Helvetica, Arial, sans-serif', '"Courier New", monospace', '"Roboto", sans-serif', '"Open Sans", sans-serif', '"Lato", sans-serif', '"Montserrat", sans-serif', '"Playfair Display", serif', '"Inter", sans-serif', '"Poppins", sans-serif', '"Raleway", sans-serif');
  CREATE TYPE "public"."enum__pages_v_blocks_layout_drop_block_height_mode" AS ENUM('auto', 'viewport', 'custom');
  CREATE TYPE "public"."enum__pages_v_blocks_layout_drop_background_type" AS ENUM('color', 'image', 'video');
  CREATE TYPE "public"."enum__pages_v_blocks_layout_drop_background_color_mode" AS ENUM('solid', 'gradient');
  CREATE TYPE "public"."enum__pages_v_blocks_layout_drop_gradient_direction" AS ENUM('to-right', 'to-left', 'to-bottom', 'to-top', 'diagonal-down', 'diagonal-up');
  ALTER TABLE "pages_blocks_layout_drop" ADD COLUMN "header_style_text_color" varchar;
  ALTER TABLE "pages_blocks_layout_drop" ADD COLUMN "header_style_bold_text_color" varchar;
  ALTER TABLE "pages_blocks_layout_drop" ADD COLUMN "header_style_use_font_group" boolean DEFAULT false;
  ALTER TABLE "pages_blocks_layout_drop" ADD COLUMN "header_style_font_group_id" integer;
  ALTER TABLE "pages_blocks_layout_drop" ADD COLUMN "header_style_font_family" "enum_pages_blocks_layout_drop_header_style_font_family" DEFAULT 'default';
  ALTER TABLE "pages_blocks_layout_drop" ADD COLUMN "header_style_use_custom_font" boolean DEFAULT false;
  ALTER TABLE "pages_blocks_layout_drop" ADD COLUMN "header_style_custom_font_file_id" integer;
  ALTER TABLE "pages_blocks_layout_drop" ADD COLUMN "header_style_custom_font_name" varchar;
  ALTER TABLE "pages_blocks_layout_drop" ADD COLUMN "elements_style_border_color" varchar DEFAULT '#e5e7eb';
  ALTER TABLE "pages_blocks_layout_drop" ADD COLUMN "elements_style_shadow" "enum_pages_blocks_layout_drop_elements_style_shadow" DEFAULT 'none';
  ALTER TABLE "pages_blocks_layout_drop" ADD COLUMN "elements_style_text_color" varchar;
  ALTER TABLE "pages_blocks_layout_drop" ADD COLUMN "elements_style_bold_text_color" varchar;
  ALTER TABLE "pages_blocks_layout_drop" ADD COLUMN "elements_style_use_font_group" boolean DEFAULT false;
  ALTER TABLE "pages_blocks_layout_drop" ADD COLUMN "elements_style_font_group_id" integer;
  ALTER TABLE "pages_blocks_layout_drop" ADD COLUMN "elements_style_font_family" "enum_pages_blocks_layout_drop_elements_style_font_family" DEFAULT 'default';
  ALTER TABLE "pages_blocks_layout_drop" ADD COLUMN "elements_style_use_custom_font" boolean DEFAULT false;
  ALTER TABLE "pages_blocks_layout_drop" ADD COLUMN "elements_style_custom_font_file_id" integer;
  ALTER TABLE "pages_blocks_layout_drop" ADD COLUMN "elements_style_custom_font_name" varchar;
  ALTER TABLE "pages_blocks_layout_drop" ADD COLUMN "contact_form_border_color" varchar DEFAULT '#e5e7eb';
  ALTER TABLE "pages_blocks_layout_drop" ADD COLUMN "contact_form_shadow" "enum_pages_blocks_layout_drop_contact_form_shadow" DEFAULT 'lg';
  ALTER TABLE "pages_blocks_layout_drop" ADD COLUMN "contact_form_text_color" varchar;
  ALTER TABLE "pages_blocks_layout_drop" ADD COLUMN "contact_form_bold_text_color" varchar;
  ALTER TABLE "pages_blocks_layout_drop" ADD COLUMN "contact_form_use_font_group" boolean DEFAULT false;
  ALTER TABLE "pages_blocks_layout_drop" ADD COLUMN "contact_form_font_group_id" integer;
  ALTER TABLE "pages_blocks_layout_drop" ADD COLUMN "contact_form_font_family" "enum_pages_blocks_layout_drop_contact_form_font_family" DEFAULT 'default';
  ALTER TABLE "pages_blocks_layout_drop" ADD COLUMN "contact_form_use_custom_font" boolean DEFAULT false;
  ALTER TABLE "pages_blocks_layout_drop" ADD COLUMN "contact_form_custom_font_file_id" integer;
  ALTER TABLE "pages_blocks_layout_drop" ADD COLUMN "contact_form_custom_font_name" varchar;
  ALTER TABLE "pages_blocks_layout_drop" ADD COLUMN "privacy_policy_text_color" varchar;
  ALTER TABLE "pages_blocks_layout_drop" ADD COLUMN "privacy_policy_bold_text_color" varchar;
  ALTER TABLE "pages_blocks_layout_drop" ADD COLUMN "privacy_policy_use_font_group" boolean DEFAULT false;
  ALTER TABLE "pages_blocks_layout_drop" ADD COLUMN "privacy_policy_font_group_id" integer;
  ALTER TABLE "pages_blocks_layout_drop" ADD COLUMN "privacy_policy_font_family" "enum_pages_blocks_layout_drop_privacy_policy_font_family" DEFAULT 'default';
  ALTER TABLE "pages_blocks_layout_drop" ADD COLUMN "privacy_policy_use_custom_font" boolean DEFAULT false;
  ALTER TABLE "pages_blocks_layout_drop" ADD COLUMN "privacy_policy_custom_font_file_id" integer;
  ALTER TABLE "pages_blocks_layout_drop" ADD COLUMN "privacy_policy_custom_font_name" varchar;
  ALTER TABLE "pages_blocks_layout_drop" ADD COLUMN "block_height_mode" "enum_pages_blocks_layout_drop_block_height_mode" DEFAULT 'auto';
  ALTER TABLE "pages_blocks_layout_drop" ADD COLUMN "custom_block_height_px" numeric;
  ALTER TABLE "pages_blocks_layout_drop" ADD COLUMN "background_type" "enum_pages_blocks_layout_drop_background_type" DEFAULT 'color';
  ALTER TABLE "pages_blocks_layout_drop" ADD COLUMN "video_youtube_url" varchar;
  ALTER TABLE "pages_blocks_layout_drop" ADD COLUMN "background_image_id" integer;
  ALTER TABLE "pages_blocks_layout_drop" ADD COLUMN "background_color_mode" "enum_pages_blocks_layout_drop_background_color_mode" DEFAULT 'solid';
  ALTER TABLE "pages_blocks_layout_drop" ADD COLUMN "gradient_start_color" varchar;
  ALTER TABLE "pages_blocks_layout_drop" ADD COLUMN "gradient_end_color" varchar;
  ALTER TABLE "pages_blocks_layout_drop" ADD COLUMN "gradient_direction" "enum_pages_blocks_layout_drop_gradient_direction" DEFAULT 'to-right';
  ALTER TABLE "pages_blocks_layout_drop" ADD COLUMN "apply_custom_width" boolean DEFAULT false;
  ALTER TABLE "pages_blocks_layout_drop" ADD COLUMN "custom_width_percent" numeric DEFAULT 100;
  ALTER TABLE "pages_blocks_layout_drop" ADD COLUMN "custom_width_percent_mobile" numeric;
  ALTER TABLE "_pages_v_blocks_layout_drop" ADD COLUMN "header_style_text_color" varchar;
  ALTER TABLE "_pages_v_blocks_layout_drop" ADD COLUMN "header_style_bold_text_color" varchar;
  ALTER TABLE "_pages_v_blocks_layout_drop" ADD COLUMN "header_style_use_font_group" boolean DEFAULT false;
  ALTER TABLE "_pages_v_blocks_layout_drop" ADD COLUMN "header_style_font_group_id" integer;
  ALTER TABLE "_pages_v_blocks_layout_drop" ADD COLUMN "header_style_font_family" "enum__pages_v_blocks_layout_drop_header_style_font_family" DEFAULT 'default';
  ALTER TABLE "_pages_v_blocks_layout_drop" ADD COLUMN "header_style_use_custom_font" boolean DEFAULT false;
  ALTER TABLE "_pages_v_blocks_layout_drop" ADD COLUMN "header_style_custom_font_file_id" integer;
  ALTER TABLE "_pages_v_blocks_layout_drop" ADD COLUMN "header_style_custom_font_name" varchar;
  ALTER TABLE "_pages_v_blocks_layout_drop" ADD COLUMN "elements_style_border_color" varchar DEFAULT '#e5e7eb';
  ALTER TABLE "_pages_v_blocks_layout_drop" ADD COLUMN "elements_style_shadow" "enum__pages_v_blocks_layout_drop_elements_style_shadow" DEFAULT 'none';
  ALTER TABLE "_pages_v_blocks_layout_drop" ADD COLUMN "elements_style_text_color" varchar;
  ALTER TABLE "_pages_v_blocks_layout_drop" ADD COLUMN "elements_style_bold_text_color" varchar;
  ALTER TABLE "_pages_v_blocks_layout_drop" ADD COLUMN "elements_style_use_font_group" boolean DEFAULT false;
  ALTER TABLE "_pages_v_blocks_layout_drop" ADD COLUMN "elements_style_font_group_id" integer;
  ALTER TABLE "_pages_v_blocks_layout_drop" ADD COLUMN "elements_style_font_family" "enum__pages_v_blocks_layout_drop_elements_style_font_family" DEFAULT 'default';
  ALTER TABLE "_pages_v_blocks_layout_drop" ADD COLUMN "elements_style_use_custom_font" boolean DEFAULT false;
  ALTER TABLE "_pages_v_blocks_layout_drop" ADD COLUMN "elements_style_custom_font_file_id" integer;
  ALTER TABLE "_pages_v_blocks_layout_drop" ADD COLUMN "elements_style_custom_font_name" varchar;
  ALTER TABLE "_pages_v_blocks_layout_drop" ADD COLUMN "contact_form_border_color" varchar DEFAULT '#e5e7eb';
  ALTER TABLE "_pages_v_blocks_layout_drop" ADD COLUMN "contact_form_shadow" "enum__pages_v_blocks_layout_drop_contact_form_shadow" DEFAULT 'lg';
  ALTER TABLE "_pages_v_blocks_layout_drop" ADD COLUMN "contact_form_text_color" varchar;
  ALTER TABLE "_pages_v_blocks_layout_drop" ADD COLUMN "contact_form_bold_text_color" varchar;
  ALTER TABLE "_pages_v_blocks_layout_drop" ADD COLUMN "contact_form_use_font_group" boolean DEFAULT false;
  ALTER TABLE "_pages_v_blocks_layout_drop" ADD COLUMN "contact_form_font_group_id" integer;
  ALTER TABLE "_pages_v_blocks_layout_drop" ADD COLUMN "contact_form_font_family" "enum__pages_v_blocks_layout_drop_contact_form_font_family" DEFAULT 'default';
  ALTER TABLE "_pages_v_blocks_layout_drop" ADD COLUMN "contact_form_use_custom_font" boolean DEFAULT false;
  ALTER TABLE "_pages_v_blocks_layout_drop" ADD COLUMN "contact_form_custom_font_file_id" integer;
  ALTER TABLE "_pages_v_blocks_layout_drop" ADD COLUMN "contact_form_custom_font_name" varchar;
  ALTER TABLE "_pages_v_blocks_layout_drop" ADD COLUMN "privacy_policy_text_color" varchar;
  ALTER TABLE "_pages_v_blocks_layout_drop" ADD COLUMN "privacy_policy_bold_text_color" varchar;
  ALTER TABLE "_pages_v_blocks_layout_drop" ADD COLUMN "privacy_policy_use_font_group" boolean DEFAULT false;
  ALTER TABLE "_pages_v_blocks_layout_drop" ADD COLUMN "privacy_policy_font_group_id" integer;
  ALTER TABLE "_pages_v_blocks_layout_drop" ADD COLUMN "privacy_policy_font_family" "enum__pages_v_blocks_layout_drop_privacy_policy_font_family" DEFAULT 'default';
  ALTER TABLE "_pages_v_blocks_layout_drop" ADD COLUMN "privacy_policy_use_custom_font" boolean DEFAULT false;
  ALTER TABLE "_pages_v_blocks_layout_drop" ADD COLUMN "privacy_policy_custom_font_file_id" integer;
  ALTER TABLE "_pages_v_blocks_layout_drop" ADD COLUMN "privacy_policy_custom_font_name" varchar;
  ALTER TABLE "_pages_v_blocks_layout_drop" ADD COLUMN "block_height_mode" "enum__pages_v_blocks_layout_drop_block_height_mode" DEFAULT 'auto';
  ALTER TABLE "_pages_v_blocks_layout_drop" ADD COLUMN "custom_block_height_px" numeric;
  ALTER TABLE "_pages_v_blocks_layout_drop" ADD COLUMN "background_type" "enum__pages_v_blocks_layout_drop_background_type" DEFAULT 'color';
  ALTER TABLE "_pages_v_blocks_layout_drop" ADD COLUMN "video_youtube_url" varchar;
  ALTER TABLE "_pages_v_blocks_layout_drop" ADD COLUMN "background_image_id" integer;
  ALTER TABLE "_pages_v_blocks_layout_drop" ADD COLUMN "background_color_mode" "enum__pages_v_blocks_layout_drop_background_color_mode" DEFAULT 'solid';
  ALTER TABLE "_pages_v_blocks_layout_drop" ADD COLUMN "gradient_start_color" varchar;
  ALTER TABLE "_pages_v_blocks_layout_drop" ADD COLUMN "gradient_end_color" varchar;
  ALTER TABLE "_pages_v_blocks_layout_drop" ADD COLUMN "gradient_direction" "enum__pages_v_blocks_layout_drop_gradient_direction" DEFAULT 'to-right';
  ALTER TABLE "_pages_v_blocks_layout_drop" ADD COLUMN "apply_custom_width" boolean DEFAULT false;
  ALTER TABLE "_pages_v_blocks_layout_drop" ADD COLUMN "custom_width_percent" numeric DEFAULT 100;
  ALTER TABLE "_pages_v_blocks_layout_drop" ADD COLUMN "custom_width_percent_mobile" numeric;
  ALTER TABLE "pages_blocks_layout_drop" ADD CONSTRAINT "pages_blocks_layout_drop_header_style_font_group_id_font_groups_id_fk" FOREIGN KEY ("header_style_font_group_id") REFERENCES "public"."font_groups"("id") ON DELETE set null ON UPDATE no action;
  ALTER TABLE "pages_blocks_layout_drop" ADD CONSTRAINT "pages_blocks_layout_drop_header_style_custom_font_file_id_fonts_id_fk" FOREIGN KEY ("header_style_custom_font_file_id") REFERENCES "public"."fonts"("id") ON DELETE set null ON UPDATE no action;
  ALTER TABLE "pages_blocks_layout_drop" ADD CONSTRAINT "pages_blocks_layout_drop_elements_style_font_group_id_font_groups_id_fk" FOREIGN KEY ("elements_style_font_group_id") REFERENCES "public"."font_groups"("id") ON DELETE set null ON UPDATE no action;
  ALTER TABLE "pages_blocks_layout_drop" ADD CONSTRAINT "pages_blocks_layout_drop_elements_style_custom_font_file_id_fonts_id_fk" FOREIGN KEY ("elements_style_custom_font_file_id") REFERENCES "public"."fonts"("id") ON DELETE set null ON UPDATE no action;
  ALTER TABLE "pages_blocks_layout_drop" ADD CONSTRAINT "pages_blocks_layout_drop_contact_form_font_group_id_font_groups_id_fk" FOREIGN KEY ("contact_form_font_group_id") REFERENCES "public"."font_groups"("id") ON DELETE set null ON UPDATE no action;
  ALTER TABLE "pages_blocks_layout_drop" ADD CONSTRAINT "pages_blocks_layout_drop_contact_form_custom_font_file_id_fonts_id_fk" FOREIGN KEY ("contact_form_custom_font_file_id") REFERENCES "public"."fonts"("id") ON DELETE set null ON UPDATE no action;
  ALTER TABLE "pages_blocks_layout_drop" ADD CONSTRAINT "pages_blocks_layout_drop_privacy_policy_font_group_id_font_groups_id_fk" FOREIGN KEY ("privacy_policy_font_group_id") REFERENCES "public"."font_groups"("id") ON DELETE set null ON UPDATE no action;
  ALTER TABLE "pages_blocks_layout_drop" ADD CONSTRAINT "pages_blocks_layout_drop_privacy_policy_custom_font_file_id_fonts_id_fk" FOREIGN KEY ("privacy_policy_custom_font_file_id") REFERENCES "public"."fonts"("id") ON DELETE set null ON UPDATE no action;
  ALTER TABLE "pages_blocks_layout_drop" ADD CONSTRAINT "pages_blocks_layout_drop_background_image_id_media_id_fk" FOREIGN KEY ("background_image_id") REFERENCES "public"."media"("id") ON DELETE set null ON UPDATE no action;
  ALTER TABLE "_pages_v_blocks_layout_drop" ADD CONSTRAINT "_pages_v_blocks_layout_drop_header_style_font_group_id_font_groups_id_fk" FOREIGN KEY ("header_style_font_group_id") REFERENCES "public"."font_groups"("id") ON DELETE set null ON UPDATE no action;
  ALTER TABLE "_pages_v_blocks_layout_drop" ADD CONSTRAINT "_pages_v_blocks_layout_drop_header_style_custom_font_file_id_fonts_id_fk" FOREIGN KEY ("header_style_custom_font_file_id") REFERENCES "public"."fonts"("id") ON DELETE set null ON UPDATE no action;
  ALTER TABLE "_pages_v_blocks_layout_drop" ADD CONSTRAINT "_pages_v_blocks_layout_drop_elements_style_font_group_id_font_groups_id_fk" FOREIGN KEY ("elements_style_font_group_id") REFERENCES "public"."font_groups"("id") ON DELETE set null ON UPDATE no action;
  ALTER TABLE "_pages_v_blocks_layout_drop" ADD CONSTRAINT "_pages_v_blocks_layout_drop_elements_style_custom_font_file_id_fonts_id_fk" FOREIGN KEY ("elements_style_custom_font_file_id") REFERENCES "public"."fonts"("id") ON DELETE set null ON UPDATE no action;
  ALTER TABLE "_pages_v_blocks_layout_drop" ADD CONSTRAINT "_pages_v_blocks_layout_drop_contact_form_font_group_id_font_groups_id_fk" FOREIGN KEY ("contact_form_font_group_id") REFERENCES "public"."font_groups"("id") ON DELETE set null ON UPDATE no action;
  ALTER TABLE "_pages_v_blocks_layout_drop" ADD CONSTRAINT "_pages_v_blocks_layout_drop_contact_form_custom_font_file_id_fonts_id_fk" FOREIGN KEY ("contact_form_custom_font_file_id") REFERENCES "public"."fonts"("id") ON DELETE set null ON UPDATE no action;
  ALTER TABLE "_pages_v_blocks_layout_drop" ADD CONSTRAINT "_pages_v_blocks_layout_drop_privacy_policy_font_group_id_font_groups_id_fk" FOREIGN KEY ("privacy_policy_font_group_id") REFERENCES "public"."font_groups"("id") ON DELETE set null ON UPDATE no action;
  ALTER TABLE "_pages_v_blocks_layout_drop" ADD CONSTRAINT "_pages_v_blocks_layout_drop_privacy_policy_custom_font_file_id_fonts_id_fk" FOREIGN KEY ("privacy_policy_custom_font_file_id") REFERENCES "public"."fonts"("id") ON DELETE set null ON UPDATE no action;
  ALTER TABLE "_pages_v_blocks_layout_drop" ADD CONSTRAINT "_pages_v_blocks_layout_drop_background_image_id_media_id_fk" FOREIGN KEY ("background_image_id") REFERENCES "public"."media"("id") ON DELETE set null ON UPDATE no action;
  CREATE INDEX "pages_blocks_layout_drop_header_style_header_style_font__idx" ON "pages_blocks_layout_drop" USING btree ("header_style_font_group_id");
  CREATE INDEX "pages_blocks_layout_drop_header_style_header_style_custo_idx" ON "pages_blocks_layout_drop" USING btree ("header_style_custom_font_file_id");
  CREATE INDEX "pages_blocks_layout_drop_elements_style_elements_style_f_idx" ON "pages_blocks_layout_drop" USING btree ("elements_style_font_group_id");
  CREATE INDEX "pages_blocks_layout_drop_elements_style_elements_style_c_idx" ON "pages_blocks_layout_drop" USING btree ("elements_style_custom_font_file_id");
  CREATE INDEX "pages_blocks_layout_drop_contact_form_contact_form_font__idx" ON "pages_blocks_layout_drop" USING btree ("contact_form_font_group_id");
  CREATE INDEX "pages_blocks_layout_drop_contact_form_contact_form_custo_idx" ON "pages_blocks_layout_drop" USING btree ("contact_form_custom_font_file_id");
  CREATE INDEX "pages_blocks_layout_drop_privacy_policy_privacy_policy_f_idx" ON "pages_blocks_layout_drop" USING btree ("privacy_policy_font_group_id");
  CREATE INDEX "pages_blocks_layout_drop_privacy_policy_privacy_policy_c_idx" ON "pages_blocks_layout_drop" USING btree ("privacy_policy_custom_font_file_id");
  CREATE INDEX "pages_blocks_layout_drop_background_image_idx" ON "pages_blocks_layout_drop" USING btree ("background_image_id");
  CREATE INDEX "_pages_v_blocks_layout_drop_header_style_header_style_fo_idx" ON "_pages_v_blocks_layout_drop" USING btree ("header_style_font_group_id");
  CREATE INDEX "_pages_v_blocks_layout_drop_header_style_header_style_cu_idx" ON "_pages_v_blocks_layout_drop" USING btree ("header_style_custom_font_file_id");
  CREATE INDEX "_pages_v_blocks_layout_drop_elements_style_elements_styl_idx" ON "_pages_v_blocks_layout_drop" USING btree ("elements_style_font_group_id");
  CREATE INDEX "_pages_v_blocks_layout_drop_elements_style_elements_st_1_idx" ON "_pages_v_blocks_layout_drop" USING btree ("elements_style_custom_font_file_id");
  CREATE INDEX "_pages_v_blocks_layout_drop_contact_form_contact_form_fo_idx" ON "_pages_v_blocks_layout_drop" USING btree ("contact_form_font_group_id");
  CREATE INDEX "_pages_v_blocks_layout_drop_contact_form_contact_form_cu_idx" ON "_pages_v_blocks_layout_drop" USING btree ("contact_form_custom_font_file_id");
  CREATE INDEX "_pages_v_blocks_layout_drop_privacy_policy_privacy_polic_idx" ON "_pages_v_blocks_layout_drop" USING btree ("privacy_policy_font_group_id");
  CREATE INDEX "_pages_v_blocks_layout_drop_privacy_policy_privacy_pol_1_idx" ON "_pages_v_blocks_layout_drop" USING btree ("privacy_policy_custom_font_file_id");
  CREATE INDEX "_pages_v_blocks_layout_drop_background_image_idx" ON "_pages_v_blocks_layout_drop" USING btree ("background_image_id");`)
}

export async function down({ db, payload, req }: MigrateDownArgs): Promise<void> {
  await db.execute(sql`
   ALTER TABLE "pages_blocks_layout_drop" DROP CONSTRAINT "pages_blocks_layout_drop_header_style_font_group_id_font_groups_id_fk";
  
  ALTER TABLE "pages_blocks_layout_drop" DROP CONSTRAINT "pages_blocks_layout_drop_header_style_custom_font_file_id_fonts_id_fk";
  
  ALTER TABLE "pages_blocks_layout_drop" DROP CONSTRAINT "pages_blocks_layout_drop_elements_style_font_group_id_font_groups_id_fk";
  
  ALTER TABLE "pages_blocks_layout_drop" DROP CONSTRAINT "pages_blocks_layout_drop_elements_style_custom_font_file_id_fonts_id_fk";
  
  ALTER TABLE "pages_blocks_layout_drop" DROP CONSTRAINT "pages_blocks_layout_drop_contact_form_font_group_id_font_groups_id_fk";
  
  ALTER TABLE "pages_blocks_layout_drop" DROP CONSTRAINT "pages_blocks_layout_drop_contact_form_custom_font_file_id_fonts_id_fk";
  
  ALTER TABLE "pages_blocks_layout_drop" DROP CONSTRAINT "pages_blocks_layout_drop_privacy_policy_font_group_id_font_groups_id_fk";
  
  ALTER TABLE "pages_blocks_layout_drop" DROP CONSTRAINT "pages_blocks_layout_drop_privacy_policy_custom_font_file_id_fonts_id_fk";
  
  ALTER TABLE "pages_blocks_layout_drop" DROP CONSTRAINT "pages_blocks_layout_drop_background_image_id_media_id_fk";
  
  ALTER TABLE "_pages_v_blocks_layout_drop" DROP CONSTRAINT "_pages_v_blocks_layout_drop_header_style_font_group_id_font_groups_id_fk";
  
  ALTER TABLE "_pages_v_blocks_layout_drop" DROP CONSTRAINT "_pages_v_blocks_layout_drop_header_style_custom_font_file_id_fonts_id_fk";
  
  ALTER TABLE "_pages_v_blocks_layout_drop" DROP CONSTRAINT "_pages_v_blocks_layout_drop_elements_style_font_group_id_font_groups_id_fk";
  
  ALTER TABLE "_pages_v_blocks_layout_drop" DROP CONSTRAINT "_pages_v_blocks_layout_drop_elements_style_custom_font_file_id_fonts_id_fk";
  
  ALTER TABLE "_pages_v_blocks_layout_drop" DROP CONSTRAINT "_pages_v_blocks_layout_drop_contact_form_font_group_id_font_groups_id_fk";
  
  ALTER TABLE "_pages_v_blocks_layout_drop" DROP CONSTRAINT "_pages_v_blocks_layout_drop_contact_form_custom_font_file_id_fonts_id_fk";
  
  ALTER TABLE "_pages_v_blocks_layout_drop" DROP CONSTRAINT "_pages_v_blocks_layout_drop_privacy_policy_font_group_id_font_groups_id_fk";
  
  ALTER TABLE "_pages_v_blocks_layout_drop" DROP CONSTRAINT "_pages_v_blocks_layout_drop_privacy_policy_custom_font_file_id_fonts_id_fk";
  
  ALTER TABLE "_pages_v_blocks_layout_drop" DROP CONSTRAINT "_pages_v_blocks_layout_drop_background_image_id_media_id_fk";
  
  DROP INDEX "pages_blocks_layout_drop_header_style_header_style_font__idx";
  DROP INDEX "pages_blocks_layout_drop_header_style_header_style_custo_idx";
  DROP INDEX "pages_blocks_layout_drop_elements_style_elements_style_f_idx";
  DROP INDEX "pages_blocks_layout_drop_elements_style_elements_style_c_idx";
  DROP INDEX "pages_blocks_layout_drop_contact_form_contact_form_font__idx";
  DROP INDEX "pages_blocks_layout_drop_contact_form_contact_form_custo_idx";
  DROP INDEX "pages_blocks_layout_drop_privacy_policy_privacy_policy_f_idx";
  DROP INDEX "pages_blocks_layout_drop_privacy_policy_privacy_policy_c_idx";
  DROP INDEX "pages_blocks_layout_drop_background_image_idx";
  DROP INDEX "_pages_v_blocks_layout_drop_header_style_header_style_fo_idx";
  DROP INDEX "_pages_v_blocks_layout_drop_header_style_header_style_cu_idx";
  DROP INDEX "_pages_v_blocks_layout_drop_elements_style_elements_styl_idx";
  DROP INDEX "_pages_v_blocks_layout_drop_elements_style_elements_st_1_idx";
  DROP INDEX "_pages_v_blocks_layout_drop_contact_form_contact_form_fo_idx";
  DROP INDEX "_pages_v_blocks_layout_drop_contact_form_contact_form_cu_idx";
  DROP INDEX "_pages_v_blocks_layout_drop_privacy_policy_privacy_polic_idx";
  DROP INDEX "_pages_v_blocks_layout_drop_privacy_policy_privacy_pol_1_idx";
  DROP INDEX "_pages_v_blocks_layout_drop_background_image_idx";
  ALTER TABLE "pages_blocks_layout_drop" DROP COLUMN "header_style_text_color";
  ALTER TABLE "pages_blocks_layout_drop" DROP COLUMN "header_style_bold_text_color";
  ALTER TABLE "pages_blocks_layout_drop" DROP COLUMN "header_style_use_font_group";
  ALTER TABLE "pages_blocks_layout_drop" DROP COLUMN "header_style_font_group_id";
  ALTER TABLE "pages_blocks_layout_drop" DROP COLUMN "header_style_font_family";
  ALTER TABLE "pages_blocks_layout_drop" DROP COLUMN "header_style_use_custom_font";
  ALTER TABLE "pages_blocks_layout_drop" DROP COLUMN "header_style_custom_font_file_id";
  ALTER TABLE "pages_blocks_layout_drop" DROP COLUMN "header_style_custom_font_name";
  ALTER TABLE "pages_blocks_layout_drop" DROP COLUMN "elements_style_border_color";
  ALTER TABLE "pages_blocks_layout_drop" DROP COLUMN "elements_style_shadow";
  ALTER TABLE "pages_blocks_layout_drop" DROP COLUMN "elements_style_text_color";
  ALTER TABLE "pages_blocks_layout_drop" DROP COLUMN "elements_style_bold_text_color";
  ALTER TABLE "pages_blocks_layout_drop" DROP COLUMN "elements_style_use_font_group";
  ALTER TABLE "pages_blocks_layout_drop" DROP COLUMN "elements_style_font_group_id";
  ALTER TABLE "pages_blocks_layout_drop" DROP COLUMN "elements_style_font_family";
  ALTER TABLE "pages_blocks_layout_drop" DROP COLUMN "elements_style_use_custom_font";
  ALTER TABLE "pages_blocks_layout_drop" DROP COLUMN "elements_style_custom_font_file_id";
  ALTER TABLE "pages_blocks_layout_drop" DROP COLUMN "elements_style_custom_font_name";
  ALTER TABLE "pages_blocks_layout_drop" DROP COLUMN "contact_form_border_color";
  ALTER TABLE "pages_blocks_layout_drop" DROP COLUMN "contact_form_shadow";
  ALTER TABLE "pages_blocks_layout_drop" DROP COLUMN "contact_form_text_color";
  ALTER TABLE "pages_blocks_layout_drop" DROP COLUMN "contact_form_bold_text_color";
  ALTER TABLE "pages_blocks_layout_drop" DROP COLUMN "contact_form_use_font_group";
  ALTER TABLE "pages_blocks_layout_drop" DROP COLUMN "contact_form_font_group_id";
  ALTER TABLE "pages_blocks_layout_drop" DROP COLUMN "contact_form_font_family";
  ALTER TABLE "pages_blocks_layout_drop" DROP COLUMN "contact_form_use_custom_font";
  ALTER TABLE "pages_blocks_layout_drop" DROP COLUMN "contact_form_custom_font_file_id";
  ALTER TABLE "pages_blocks_layout_drop" DROP COLUMN "contact_form_custom_font_name";
  ALTER TABLE "pages_blocks_layout_drop" DROP COLUMN "privacy_policy_text_color";
  ALTER TABLE "pages_blocks_layout_drop" DROP COLUMN "privacy_policy_bold_text_color";
  ALTER TABLE "pages_blocks_layout_drop" DROP COLUMN "privacy_policy_use_font_group";
  ALTER TABLE "pages_blocks_layout_drop" DROP COLUMN "privacy_policy_font_group_id";
  ALTER TABLE "pages_blocks_layout_drop" DROP COLUMN "privacy_policy_font_family";
  ALTER TABLE "pages_blocks_layout_drop" DROP COLUMN "privacy_policy_use_custom_font";
  ALTER TABLE "pages_blocks_layout_drop" DROP COLUMN "privacy_policy_custom_font_file_id";
  ALTER TABLE "pages_blocks_layout_drop" DROP COLUMN "privacy_policy_custom_font_name";
  ALTER TABLE "pages_blocks_layout_drop" DROP COLUMN "block_height_mode";
  ALTER TABLE "pages_blocks_layout_drop" DROP COLUMN "custom_block_height_px";
  ALTER TABLE "pages_blocks_layout_drop" DROP COLUMN "background_type";
  ALTER TABLE "pages_blocks_layout_drop" DROP COLUMN "video_youtube_url";
  ALTER TABLE "pages_blocks_layout_drop" DROP COLUMN "background_image_id";
  ALTER TABLE "pages_blocks_layout_drop" DROP COLUMN "background_color_mode";
  ALTER TABLE "pages_blocks_layout_drop" DROP COLUMN "gradient_start_color";
  ALTER TABLE "pages_blocks_layout_drop" DROP COLUMN "gradient_end_color";
  ALTER TABLE "pages_blocks_layout_drop" DROP COLUMN "gradient_direction";
  ALTER TABLE "pages_blocks_layout_drop" DROP COLUMN "apply_custom_width";
  ALTER TABLE "pages_blocks_layout_drop" DROP COLUMN "custom_width_percent";
  ALTER TABLE "pages_blocks_layout_drop" DROP COLUMN "custom_width_percent_mobile";
  ALTER TABLE "_pages_v_blocks_layout_drop" DROP COLUMN "header_style_text_color";
  ALTER TABLE "_pages_v_blocks_layout_drop" DROP COLUMN "header_style_bold_text_color";
  ALTER TABLE "_pages_v_blocks_layout_drop" DROP COLUMN "header_style_use_font_group";
  ALTER TABLE "_pages_v_blocks_layout_drop" DROP COLUMN "header_style_font_group_id";
  ALTER TABLE "_pages_v_blocks_layout_drop" DROP COLUMN "header_style_font_family";
  ALTER TABLE "_pages_v_blocks_layout_drop" DROP COLUMN "header_style_use_custom_font";
  ALTER TABLE "_pages_v_blocks_layout_drop" DROP COLUMN "header_style_custom_font_file_id";
  ALTER TABLE "_pages_v_blocks_layout_drop" DROP COLUMN "header_style_custom_font_name";
  ALTER TABLE "_pages_v_blocks_layout_drop" DROP COLUMN "elements_style_border_color";
  ALTER TABLE "_pages_v_blocks_layout_drop" DROP COLUMN "elements_style_shadow";
  ALTER TABLE "_pages_v_blocks_layout_drop" DROP COLUMN "elements_style_text_color";
  ALTER TABLE "_pages_v_blocks_layout_drop" DROP COLUMN "elements_style_bold_text_color";
  ALTER TABLE "_pages_v_blocks_layout_drop" DROP COLUMN "elements_style_use_font_group";
  ALTER TABLE "_pages_v_blocks_layout_drop" DROP COLUMN "elements_style_font_group_id";
  ALTER TABLE "_pages_v_blocks_layout_drop" DROP COLUMN "elements_style_font_family";
  ALTER TABLE "_pages_v_blocks_layout_drop" DROP COLUMN "elements_style_use_custom_font";
  ALTER TABLE "_pages_v_blocks_layout_drop" DROP COLUMN "elements_style_custom_font_file_id";
  ALTER TABLE "_pages_v_blocks_layout_drop" DROP COLUMN "elements_style_custom_font_name";
  ALTER TABLE "_pages_v_blocks_layout_drop" DROP COLUMN "contact_form_border_color";
  ALTER TABLE "_pages_v_blocks_layout_drop" DROP COLUMN "contact_form_shadow";
  ALTER TABLE "_pages_v_blocks_layout_drop" DROP COLUMN "contact_form_text_color";
  ALTER TABLE "_pages_v_blocks_layout_drop" DROP COLUMN "contact_form_bold_text_color";
  ALTER TABLE "_pages_v_blocks_layout_drop" DROP COLUMN "contact_form_use_font_group";
  ALTER TABLE "_pages_v_blocks_layout_drop" DROP COLUMN "contact_form_font_group_id";
  ALTER TABLE "_pages_v_blocks_layout_drop" DROP COLUMN "contact_form_font_family";
  ALTER TABLE "_pages_v_blocks_layout_drop" DROP COLUMN "contact_form_use_custom_font";
  ALTER TABLE "_pages_v_blocks_layout_drop" DROP COLUMN "contact_form_custom_font_file_id";
  ALTER TABLE "_pages_v_blocks_layout_drop" DROP COLUMN "contact_form_custom_font_name";
  ALTER TABLE "_pages_v_blocks_layout_drop" DROP COLUMN "privacy_policy_text_color";
  ALTER TABLE "_pages_v_blocks_layout_drop" DROP COLUMN "privacy_policy_bold_text_color";
  ALTER TABLE "_pages_v_blocks_layout_drop" DROP COLUMN "privacy_policy_use_font_group";
  ALTER TABLE "_pages_v_blocks_layout_drop" DROP COLUMN "privacy_policy_font_group_id";
  ALTER TABLE "_pages_v_blocks_layout_drop" DROP COLUMN "privacy_policy_font_family";
  ALTER TABLE "_pages_v_blocks_layout_drop" DROP COLUMN "privacy_policy_use_custom_font";
  ALTER TABLE "_pages_v_blocks_layout_drop" DROP COLUMN "privacy_policy_custom_font_file_id";
  ALTER TABLE "_pages_v_blocks_layout_drop" DROP COLUMN "privacy_policy_custom_font_name";
  ALTER TABLE "_pages_v_blocks_layout_drop" DROP COLUMN "block_height_mode";
  ALTER TABLE "_pages_v_blocks_layout_drop" DROP COLUMN "custom_block_height_px";
  ALTER TABLE "_pages_v_blocks_layout_drop" DROP COLUMN "background_type";
  ALTER TABLE "_pages_v_blocks_layout_drop" DROP COLUMN "video_youtube_url";
  ALTER TABLE "_pages_v_blocks_layout_drop" DROP COLUMN "background_image_id";
  ALTER TABLE "_pages_v_blocks_layout_drop" DROP COLUMN "background_color_mode";
  ALTER TABLE "_pages_v_blocks_layout_drop" DROP COLUMN "gradient_start_color";
  ALTER TABLE "_pages_v_blocks_layout_drop" DROP COLUMN "gradient_end_color";
  ALTER TABLE "_pages_v_blocks_layout_drop" DROP COLUMN "gradient_direction";
  ALTER TABLE "_pages_v_blocks_layout_drop" DROP COLUMN "apply_custom_width";
  ALTER TABLE "_pages_v_blocks_layout_drop" DROP COLUMN "custom_width_percent";
  ALTER TABLE "_pages_v_blocks_layout_drop" DROP COLUMN "custom_width_percent_mobile";
  DROP TYPE "public"."enum_pages_blocks_layout_drop_header_style_font_family";
  DROP TYPE "public"."enum_pages_blocks_layout_drop_elements_style_shadow";
  DROP TYPE "public"."enum_pages_blocks_layout_drop_elements_style_font_family";
  DROP TYPE "public"."enum_pages_blocks_layout_drop_contact_form_shadow";
  DROP TYPE "public"."enum_pages_blocks_layout_drop_contact_form_font_family";
  DROP TYPE "public"."enum_pages_blocks_layout_drop_privacy_policy_font_family";
  DROP TYPE "public"."enum_pages_blocks_layout_drop_block_height_mode";
  DROP TYPE "public"."enum_pages_blocks_layout_drop_background_type";
  DROP TYPE "public"."enum_pages_blocks_layout_drop_background_color_mode";
  DROP TYPE "public"."enum_pages_blocks_layout_drop_gradient_direction";
  DROP TYPE "public"."enum__pages_v_blocks_layout_drop_header_style_font_family";
  DROP TYPE "public"."enum__pages_v_blocks_layout_drop_elements_style_shadow";
  DROP TYPE "public"."enum__pages_v_blocks_layout_drop_elements_style_font_family";
  DROP TYPE "public"."enum__pages_v_blocks_layout_drop_contact_form_shadow";
  DROP TYPE "public"."enum__pages_v_blocks_layout_drop_contact_form_font_family";
  DROP TYPE "public"."enum__pages_v_blocks_layout_drop_privacy_policy_font_family";
  DROP TYPE "public"."enum__pages_v_blocks_layout_drop_block_height_mode";
  DROP TYPE "public"."enum__pages_v_blocks_layout_drop_background_type";
  DROP TYPE "public"."enum__pages_v_blocks_layout_drop_background_color_mode";
  DROP TYPE "public"."enum__pages_v_blocks_layout_drop_gradient_direction";`)
}
