import { MigrateUpArgs, MigrateDownArgs, sql } from '@payloadcms/db-postgres'

export async function up({ db, payload, req }: MigrateUpArgs): Promise<void> {
  // 1. CREATE TYPE: idempotente (si ya existen, ignorar)
  await db.execute(sql`
   DO $$ BEGIN CREATE TYPE "public"."enum_pages_blocks_career4_depts4_jobs_type" AS ENUM('reference', 'custom'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
   DO $$ BEGIN CREATE TYPE "public"."enum_pages_blocks_career4_font_family" AS ENUM('default', 'Arial, sans-serif', '"Times New Roman", serif', 'Georgia, serif', 'Verdana, sans-serif', 'Helvetica, Arial, sans-serif', '"Courier New", monospace', '"Roboto", sans-serif', '"Open Sans", sans-serif', '"Lato", sans-serif', '"Montserrat", sans-serif', '"Playfair Display", serif', '"Inter", sans-serif', '"Poppins", sans-serif', '"Raleway", sans-serif'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
   DO $$ BEGIN CREATE TYPE "public"."enum_pages_blocks_career5_font_family" AS ENUM('default', 'Arial, sans-serif', '"Times New Roman", serif', 'Georgia, serif', 'Verdana, sans-serif', 'Helvetica, Arial, sans-serif', '"Courier New", monospace', '"Roboto", sans-serif', '"Open Sans", sans-serif', '"Lato", sans-serif', '"Montserrat", sans-serif', '"Playfair Display", serif', '"Inter", sans-serif', '"Poppins", sans-serif', '"Raleway", sans-serif'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
   DO $$ BEGIN CREATE TYPE "public"."enum_pages_blocks_career6_font_family" AS ENUM('default', 'Arial, sans-serif', '"Times New Roman", serif', 'Georgia, serif', 'Verdana, sans-serif', 'Helvetica, Arial, sans-serif', '"Courier New", monospace', '"Roboto", sans-serif', '"Open Sans", sans-serif', '"Lato", sans-serif', '"Montserrat", sans-serif', '"Playfair Display", serif', '"Inter", sans-serif', '"Poppins", sans-serif', '"Raleway", sans-serif'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
   DO $$ BEGIN CREATE TYPE "public"."enum_jobs_link_type" AS ENUM('reference', 'custom'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
   DO $$ BEGIN CREATE TYPE "public"."enum_pages_blocks_career_section1_font_family" AS ENUM('default', 'Arial, sans-serif', '"Times New Roman", serif', 'Georgia, serif', 'Verdana, sans-serif', 'Helvetica, Arial, sans-serif', '"Courier New", monospace', '"Roboto", sans-serif', '"Open Sans", sans-serif', '"Lato", sans-serif', '"Montserrat", sans-serif', '"Playfair Display", serif', '"Inter", sans-serif', '"Poppins", sans-serif', '"Raleway", sans-serif'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
   DO $$ BEGIN CREATE TYPE "public"."enum__pages_v_blocks_career4_depts4_jobs_type" AS ENUM('reference', 'custom'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
   DO $$ BEGIN CREATE TYPE "public"."enum__pages_v_blocks_career4_font_family" AS ENUM('default', 'Arial, sans-serif', '"Times New Roman", serif', 'Georgia, serif', 'Verdana, sans-serif', 'Helvetica, Arial, sans-serif', '"Courier New", monospace', '"Roboto", sans-serif', '"Open Sans", sans-serif', '"Lato", sans-serif', '"Montserrat", sans-serif', '"Playfair Display", serif', '"Inter", sans-serif', '"Poppins", sans-serif', '"Raleway", sans-serif'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
   DO $$ BEGIN CREATE TYPE "public"."enum__pages_v_blocks_career5_font_family" AS ENUM('default', 'Arial, sans-serif', '"Times New Roman", serif', 'Georgia, serif', 'Verdana, sans-serif', 'Helvetica, Arial, sans-serif', '"Courier New", monospace', '"Roboto", sans-serif', '"Open Sans", sans-serif', '"Lato", sans-serif', '"Montserrat", sans-serif', '"Playfair Display", serif', '"Inter", sans-serif', '"Poppins", sans-serif', '"Raleway", sans-serif'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
   DO $$ BEGIN CREATE TYPE "public"."enum__pages_v_blocks_career6_font_family" AS ENUM('default', 'Arial, sans-serif', '"Times New Roman", serif', 'Georgia, serif', 'Verdana, sans-serif', 'Helvetica, Arial, sans-serif', '"Courier New", monospace', '"Roboto", sans-serif', '"Open Sans", sans-serif', '"Lato", sans-serif', '"Montserrat", sans-serif', '"Playfair Display", serif', '"Inter", sans-serif', '"Poppins", sans-serif', '"Raleway", sans-serif'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
   DO $$ BEGIN CREATE TYPE "public"."enum__jobs_v_link_type" AS ENUM('reference', 'custom'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
   DO $$ BEGIN CREATE TYPE "public"."enum__pages_v_blocks_career_section1_font_family" AS ENUM('default', 'Arial, sans-serif', '"Times New Roman", serif', 'Georgia, serif', 'Verdana, sans-serif', 'Helvetica, Arial, sans-serif', '"Courier New", monospace', '"Roboto", sans-serif', '"Open Sans", sans-serif', '"Lato", sans-serif', '"Montserrat", sans-serif', '"Playfair Display", serif', '"Inter", sans-serif', '"Poppins", sans-serif', '"Raleway", sans-serif'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
  `)

  // 2. DROP DEFAULT en url y title varchar -> jsonb (misma lógica que 20260205_114448: un execute, DO $$ ... $$;, USING to_jsonb; CASE para idempotencia si title ya es jsonb)
  await db.execute(sql`
  DO $$ BEGIN ALTER TABLE "pages_blocks_career4_depts4_jobs" ALTER COLUMN "url" DROP DEFAULT; EXCEPTION WHEN others THEN NULL; END $$;
  DO $$ BEGIN ALTER TABLE "pages_blocks_career4_depts4" ALTER COLUMN "title" DROP DEFAULT; EXCEPTION WHEN others THEN NULL; END $$;
  DO $$ BEGIN ALTER TABLE "pages_blocks_career4_depts4" ALTER COLUMN "title" SET DATA TYPE jsonb USING (CASE WHEN pg_typeof(title) = 'jsonb'::regtype THEN title ELSE to_jsonb(title::text) END); EXCEPTION WHEN others THEN NULL; END $$;
  DO $$ BEGIN ALTER TABLE "career5_depts" ALTER COLUMN "title" DROP DEFAULT; EXCEPTION WHEN others THEN NULL; END $$;
  DO $$ BEGIN ALTER TABLE "career5_depts" ALTER COLUMN "title" SET DATA TYPE jsonb USING (CASE WHEN pg_typeof(title) = 'jsonb'::regtype THEN title ELSE to_jsonb(title::text) END); EXCEPTION WHEN others THEN NULL; END $$;
  DO $$ BEGIN ALTER TABLE "career6_depts" ALTER COLUMN "title" DROP DEFAULT; EXCEPTION WHEN others THEN NULL; END $$;
  DO $$ BEGIN ALTER TABLE "career6_depts" ALTER COLUMN "title" SET DATA TYPE jsonb USING (CASE WHEN pg_typeof(title) = 'jsonb'::regtype THEN title ELSE to_jsonb(title::text) END); EXCEPTION WHEN others THEN NULL; END $$;
  DO $$ BEGIN ALTER TABLE "depts" ALTER COLUMN "title" DROP DEFAULT; EXCEPTION WHEN others THEN NULL; END $$;
  DO $$ BEGIN ALTER TABLE "depts" ALTER COLUMN "title" SET DATA TYPE jsonb USING (CASE WHEN pg_typeof(title) = 'jsonb'::regtype THEN title ELSE to_jsonb(title::text) END); EXCEPTION WHEN others THEN NULL; END $$;
  DO $$ BEGIN ALTER TABLE "_pages_v_blocks_career4_depts4_jobs" ALTER COLUMN "url" DROP DEFAULT; EXCEPTION WHEN others THEN NULL; END $$;
  DO $$ BEGIN ALTER TABLE "_pages_v_blocks_career4_depts4" ALTER COLUMN "title" DROP DEFAULT; EXCEPTION WHEN others THEN NULL; END $$;
  DO $$ BEGIN ALTER TABLE "_pages_v_blocks_career4_depts4" ALTER COLUMN "title" SET DATA TYPE jsonb USING (CASE WHEN pg_typeof(title) = 'jsonb'::regtype THEN title ELSE to_jsonb(title::text) END); EXCEPTION WHEN others THEN NULL; END $$;
  DO $$ BEGIN ALTER TABLE "_career5_depts_v" ALTER COLUMN "title" DROP DEFAULT; EXCEPTION WHEN others THEN NULL; END $$;
  DO $$ BEGIN ALTER TABLE "_career5_depts_v" ALTER COLUMN "title" SET DATA TYPE jsonb USING (CASE WHEN pg_typeof(title) = 'jsonb'::regtype THEN title ELSE to_jsonb(title::text) END); EXCEPTION WHEN others THEN NULL; END $$;
  DO $$ BEGIN ALTER TABLE "_career6_depts_v" ALTER COLUMN "title" DROP DEFAULT; EXCEPTION WHEN others THEN NULL; END $$;
  DO $$ BEGIN ALTER TABLE "_career6_depts_v" ALTER COLUMN "title" SET DATA TYPE jsonb USING (CASE WHEN pg_typeof(title) = 'jsonb'::regtype THEN title ELSE to_jsonb(title::text) END); EXCEPTION WHEN others THEN NULL; END $$;
  DO $$ BEGIN ALTER TABLE "_depts_v" ALTER COLUMN "title" DROP DEFAULT; EXCEPTION WHEN others THEN NULL; END $$;
  DO $$ BEGIN ALTER TABLE "_depts_v" ALTER COLUMN "title" SET DATA TYPE jsonb USING (CASE WHEN pg_typeof(title) = 'jsonb'::regtype THEN title ELSE to_jsonb(title::text) END); EXCEPTION WHEN others THEN NULL; END $$;
  `)

  // 3. ADD COLUMN IF NOT EXISTS (todas las nuevas columnas)
  await db.execute(sql`
  ALTER TABLE "pages_blocks_career4_depts4_jobs" ADD COLUMN IF NOT EXISTS "job_content" jsonb;
  ALTER TABLE "pages_blocks_career4_depts4_jobs" ADD COLUMN IF NOT EXISTS "type" "enum_pages_blocks_career4_depts4_jobs_type" DEFAULT 'reference';
  ALTER TABLE "pages_blocks_career4_depts4_jobs" ADD COLUMN IF NOT EXISTS "new_tab" boolean;
  ALTER TABLE "pages_blocks_career4" ADD COLUMN IF NOT EXISTS "content" jsonb;
  ALTER TABLE "pages_blocks_career4" ADD COLUMN IF NOT EXISTS "background_color" varchar;
  ALTER TABLE "pages_blocks_career4" ADD COLUMN IF NOT EXISTS "text_color" varchar;
  ALTER TABLE "pages_blocks_career4" ADD COLUMN IF NOT EXISTS "bold_text_color" varchar;
  ALTER TABLE "pages_blocks_career4" ADD COLUMN IF NOT EXISTS "button_background_color" varchar;
  ALTER TABLE "pages_blocks_career4" ADD COLUMN IF NOT EXISTS "button_text_color" varchar;
  ALTER TABLE "pages_blocks_career4" ADD COLUMN IF NOT EXISTS "font_family" "enum_pages_blocks_career4_font_family" DEFAULT 'default';
  ALTER TABLE "pages_blocks_career4" ADD COLUMN IF NOT EXISTS "use_custom_font" boolean DEFAULT false;
  ALTER TABLE "pages_blocks_career4" ADD COLUMN IF NOT EXISTS "custom_font_file_id" integer;
  ALTER TABLE "pages_blocks_career4" ADD COLUMN IF NOT EXISTS "custom_font_name" varchar;
  ALTER TABLE "career5_jobs" ADD COLUMN IF NOT EXISTS "job_content" jsonb;
  ALTER TABLE "pages_blocks_career5" ADD COLUMN IF NOT EXISTS "content" jsonb;
  ALTER TABLE "pages_blocks_career5" ADD COLUMN IF NOT EXISTS "background_color" varchar;
  ALTER TABLE "pages_blocks_career5" ADD COLUMN IF NOT EXISTS "text_color" varchar;
  ALTER TABLE "pages_blocks_career5" ADD COLUMN IF NOT EXISTS "bold_text_color" varchar;
  ALTER TABLE "pages_blocks_career5" ADD COLUMN IF NOT EXISTS "button_background_color" varchar;
  ALTER TABLE "pages_blocks_career5" ADD COLUMN IF NOT EXISTS "button_text_color" varchar;
  ALTER TABLE "pages_blocks_career5" ADD COLUMN IF NOT EXISTS "font_family" "enum_pages_blocks_career5_font_family" DEFAULT 'default';
  ALTER TABLE "pages_blocks_career5" ADD COLUMN IF NOT EXISTS "use_custom_font" boolean DEFAULT false;
  ALTER TABLE "pages_blocks_career5" ADD COLUMN IF NOT EXISTS "custom_font_file_id" integer;
  ALTER TABLE "pages_blocks_career5" ADD COLUMN IF NOT EXISTS "custom_font_name" varchar;
  ALTER TABLE "career6_jobs" ADD COLUMN IF NOT EXISTS "job_content" jsonb;
  ALTER TABLE "pages_blocks_career6" ADD COLUMN IF NOT EXISTS "content" jsonb;
  ALTER TABLE "pages_blocks_career6" ADD COLUMN IF NOT EXISTS "background_color" varchar;
  ALTER TABLE "pages_blocks_career6" ADD COLUMN IF NOT EXISTS "text_color" varchar;
  ALTER TABLE "pages_blocks_career6" ADD COLUMN IF NOT EXISTS "bold_text_color" varchar;
  ALTER TABLE "pages_blocks_career6" ADD COLUMN IF NOT EXISTS "button_background_color" varchar;
  ALTER TABLE "pages_blocks_career6" ADD COLUMN IF NOT EXISTS "button_text_color" varchar;
  ALTER TABLE "pages_blocks_career6" ADD COLUMN IF NOT EXISTS "font_family" "enum_pages_blocks_career6_font_family" DEFAULT 'default';
  ALTER TABLE "pages_blocks_career6" ADD COLUMN IF NOT EXISTS "use_custom_font" boolean DEFAULT false;
  ALTER TABLE "pages_blocks_career6" ADD COLUMN IF NOT EXISTS "custom_font_file_id" integer;
  ALTER TABLE "pages_blocks_career6" ADD COLUMN IF NOT EXISTS "custom_font_name" varchar;
  ALTER TABLE "jobs" ADD COLUMN IF NOT EXISTS "job_content" jsonb;
  ALTER TABLE "jobs" ADD COLUMN IF NOT EXISTS "link_type" "enum_jobs_link_type" DEFAULT 'reference';
  ALTER TABLE "jobs" ADD COLUMN IF NOT EXISTS "link_new_tab" boolean;
  ALTER TABLE "jobs" ADD COLUMN IF NOT EXISTS "link_url" varchar;
  ALTER TABLE "pages_blocks_career_section1" ADD COLUMN IF NOT EXISTS "content" jsonb;
  ALTER TABLE "pages_blocks_career_section1" ADD COLUMN IF NOT EXISTS "background_color" varchar;
  ALTER TABLE "pages_blocks_career_section1" ADD COLUMN IF NOT EXISTS "text_color" varchar;
  ALTER TABLE "pages_blocks_career_section1" ADD COLUMN IF NOT EXISTS "bold_text_color" varchar;
  ALTER TABLE "pages_blocks_career_section1" ADD COLUMN IF NOT EXISTS "button_background_color" varchar;
  ALTER TABLE "pages_blocks_career_section1" ADD COLUMN IF NOT EXISTS "button_text_color" varchar;
  ALTER TABLE "pages_blocks_career_section1" ADD COLUMN IF NOT EXISTS "font_family" "enum_pages_blocks_career_section1_font_family" DEFAULT 'default';
  ALTER TABLE "pages_blocks_career_section1" ADD COLUMN IF NOT EXISTS "use_custom_font" boolean DEFAULT false;
  ALTER TABLE "pages_blocks_career_section1" ADD COLUMN IF NOT EXISTS "custom_font_file_id" integer;
  ALTER TABLE "pages_blocks_career_section1" ADD COLUMN IF NOT EXISTS "custom_font_name" varchar;
  ALTER TABLE "_pages_v_blocks_career4_depts4_jobs" ADD COLUMN IF NOT EXISTS "job_content" jsonb;
  ALTER TABLE "_pages_v_blocks_career4_depts4_jobs" ADD COLUMN IF NOT EXISTS "type" "enum__pages_v_blocks_career4_depts4_jobs_type" DEFAULT 'reference';
  ALTER TABLE "_pages_v_blocks_career4_depts4_jobs" ADD COLUMN IF NOT EXISTS "new_tab" boolean;
  ALTER TABLE "_pages_v_blocks_career4" ADD COLUMN IF NOT EXISTS "content" jsonb;
  ALTER TABLE "_pages_v_blocks_career4" ADD COLUMN IF NOT EXISTS "background_color" varchar;
  ALTER TABLE "_pages_v_blocks_career4" ADD COLUMN IF NOT EXISTS "text_color" varchar;
  ALTER TABLE "_pages_v_blocks_career4" ADD COLUMN IF NOT EXISTS "bold_text_color" varchar;
  ALTER TABLE "_pages_v_blocks_career4" ADD COLUMN IF NOT EXISTS "button_background_color" varchar;
  ALTER TABLE "_pages_v_blocks_career4" ADD COLUMN IF NOT EXISTS "button_text_color" varchar;
  ALTER TABLE "_pages_v_blocks_career4" ADD COLUMN IF NOT EXISTS "font_family" "enum__pages_v_blocks_career4_font_family" DEFAULT 'default';
  ALTER TABLE "_pages_v_blocks_career4" ADD COLUMN IF NOT EXISTS "use_custom_font" boolean DEFAULT false;
  ALTER TABLE "_pages_v_blocks_career4" ADD COLUMN IF NOT EXISTS "custom_font_file_id" integer;
  ALTER TABLE "_pages_v_blocks_career4" ADD COLUMN IF NOT EXISTS "custom_font_name" varchar;
  ALTER TABLE "_career5_jobs_v" ADD COLUMN IF NOT EXISTS "job_content" jsonb;
  ALTER TABLE "_pages_v_blocks_career5" ADD COLUMN IF NOT EXISTS "content" jsonb;
  ALTER TABLE "_pages_v_blocks_career5" ADD COLUMN IF NOT EXISTS "background_color" varchar;
  ALTER TABLE "_pages_v_blocks_career5" ADD COLUMN IF NOT EXISTS "text_color" varchar;
  ALTER TABLE "_pages_v_blocks_career5" ADD COLUMN IF NOT EXISTS "bold_text_color" varchar;
  ALTER TABLE "_pages_v_blocks_career5" ADD COLUMN IF NOT EXISTS "button_background_color" varchar;
  ALTER TABLE "_pages_v_blocks_career5" ADD COLUMN IF NOT EXISTS "button_text_color" varchar;
  ALTER TABLE "_pages_v_blocks_career5" ADD COLUMN IF NOT EXISTS "font_family" "enum__pages_v_blocks_career5_font_family" DEFAULT 'default';
  ALTER TABLE "_pages_v_blocks_career5" ADD COLUMN IF NOT EXISTS "use_custom_font" boolean DEFAULT false;
  ALTER TABLE "_pages_v_blocks_career5" ADD COLUMN IF NOT EXISTS "custom_font_file_id" integer;
  ALTER TABLE "_pages_v_blocks_career5" ADD COLUMN IF NOT EXISTS "custom_font_name" varchar;
  ALTER TABLE "_career6_jobs_v" ADD COLUMN IF NOT EXISTS "job_content" jsonb;
  ALTER TABLE "_pages_v_blocks_career6" ADD COLUMN IF NOT EXISTS "content" jsonb;
  ALTER TABLE "_pages_v_blocks_career6" ADD COLUMN IF NOT EXISTS "background_color" varchar;
  ALTER TABLE "_pages_v_blocks_career6" ADD COLUMN IF NOT EXISTS "text_color" varchar;
  ALTER TABLE "_pages_v_blocks_career6" ADD COLUMN IF NOT EXISTS "bold_text_color" varchar;
  ALTER TABLE "_pages_v_blocks_career6" ADD COLUMN IF NOT EXISTS "button_background_color" varchar;
  ALTER TABLE "_pages_v_blocks_career6" ADD COLUMN IF NOT EXISTS "button_text_color" varchar;
  ALTER TABLE "_pages_v_blocks_career6" ADD COLUMN IF NOT EXISTS "font_family" "enum__pages_v_blocks_career6_font_family" DEFAULT 'default';
  ALTER TABLE "_pages_v_blocks_career6" ADD COLUMN IF NOT EXISTS "use_custom_font" boolean DEFAULT false;
  ALTER TABLE "_pages_v_blocks_career6" ADD COLUMN IF NOT EXISTS "custom_font_file_id" integer;
  ALTER TABLE "_pages_v_blocks_career6" ADD COLUMN IF NOT EXISTS "custom_font_name" varchar;
  ALTER TABLE "_jobs_v" ADD COLUMN IF NOT EXISTS "job_content" jsonb;
  ALTER TABLE "_jobs_v" ADD COLUMN IF NOT EXISTS "link_type" "enum__jobs_v_link_type" DEFAULT 'reference';
  ALTER TABLE "_jobs_v" ADD COLUMN IF NOT EXISTS "link_new_tab" boolean;
  ALTER TABLE "_jobs_v" ADD COLUMN IF NOT EXISTS "link_url" varchar;
  ALTER TABLE "_pages_v_blocks_career_section1" ADD COLUMN IF NOT EXISTS "content" jsonb;
  ALTER TABLE "_pages_v_blocks_career_section1" ADD COLUMN IF NOT EXISTS "background_color" varchar;
  ALTER TABLE "_pages_v_blocks_career_section1" ADD COLUMN IF NOT EXISTS "text_color" varchar;
  ALTER TABLE "_pages_v_blocks_career_section1" ADD COLUMN IF NOT EXISTS "bold_text_color" varchar;
  ALTER TABLE "_pages_v_blocks_career_section1" ADD COLUMN IF NOT EXISTS "button_background_color" varchar;
  ALTER TABLE "_pages_v_blocks_career_section1" ADD COLUMN IF NOT EXISTS "button_text_color" varchar;
  ALTER TABLE "_pages_v_blocks_career_section1" ADD COLUMN IF NOT EXISTS "font_family" "enum__pages_v_blocks_career_section1_font_family" DEFAULT 'default';
  ALTER TABLE "_pages_v_blocks_career_section1" ADD COLUMN IF NOT EXISTS "use_custom_font" boolean DEFAULT false;
  ALTER TABLE "_pages_v_blocks_career_section1" ADD COLUMN IF NOT EXISTS "custom_font_file_id" integer;
  ALTER TABLE "_pages_v_blocks_career_section1" ADD COLUMN IF NOT EXISTS "custom_font_name" varchar;
  `)

  // 4. ADD CONSTRAINT (idempotente)
  await db.execute(sql`
  DO $$ BEGIN ALTER TABLE "pages_blocks_career4" ADD CONSTRAINT "pages_blocks_career4_custom_font_file_id_fonts_id_fk" FOREIGN KEY ("custom_font_file_id") REFERENCES "public"."fonts"("id") ON DELETE set null ON UPDATE no action; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
  DO $$ BEGIN ALTER TABLE "pages_blocks_career5" ADD CONSTRAINT "pages_blocks_career5_custom_font_file_id_fonts_id_fk" FOREIGN KEY ("custom_font_file_id") REFERENCES "public"."fonts"("id") ON DELETE set null ON UPDATE no action; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
  DO $$ BEGIN ALTER TABLE "pages_blocks_career6" ADD CONSTRAINT "pages_blocks_career6_custom_font_file_id_fonts_id_fk" FOREIGN KEY ("custom_font_file_id") REFERENCES "public"."fonts"("id") ON DELETE set null ON UPDATE no action; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
  DO $$ BEGIN ALTER TABLE "pages_blocks_career_section1" ADD CONSTRAINT "pages_blocks_career_section1_custom_font_file_id_fonts_id_fk" FOREIGN KEY ("custom_font_file_id") REFERENCES "public"."fonts"("id") ON DELETE set null ON UPDATE no action; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
  DO $$ BEGIN ALTER TABLE "_pages_v_blocks_career4" ADD CONSTRAINT "_pages_v_blocks_career4_custom_font_file_id_fonts_id_fk" FOREIGN KEY ("custom_font_file_id") REFERENCES "public"."fonts"("id") ON DELETE set null ON UPDATE no action; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
  DO $$ BEGIN ALTER TABLE "_pages_v_blocks_career5" ADD CONSTRAINT "_pages_v_blocks_career5_custom_font_file_id_fonts_id_fk" FOREIGN KEY ("custom_font_file_id") REFERENCES "public"."fonts"("id") ON DELETE set null ON UPDATE no action; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
  DO $$ BEGIN ALTER TABLE "_pages_v_blocks_career6" ADD CONSTRAINT "_pages_v_blocks_career6_custom_font_file_id_fonts_id_fk" FOREIGN KEY ("custom_font_file_id") REFERENCES "public"."fonts"("id") ON DELETE set null ON UPDATE no action; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
  DO $$ BEGIN ALTER TABLE "_pages_v_blocks_career_section1" ADD CONSTRAINT "_pages_v_blocks_career_section1_custom_font_file_id_fonts_id_fk" FOREIGN KEY ("custom_font_file_id") REFERENCES "public"."fonts"("id") ON DELETE set null ON UPDATE no action; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
  CREATE INDEX IF NOT EXISTS "pages_blocks_career4_custom_font_file_idx" ON "pages_blocks_career4" USING btree ("custom_font_file_id");
  CREATE INDEX IF NOT EXISTS "pages_blocks_career5_custom_font_file_idx" ON "pages_blocks_career5" USING btree ("custom_font_file_id");
  CREATE INDEX IF NOT EXISTS "pages_blocks_career6_custom_font_file_idx" ON "pages_blocks_career6" USING btree ("custom_font_file_id");
  CREATE INDEX IF NOT EXISTS "pages_blocks_career_section1_custom_font_file_idx" ON "pages_blocks_career_section1" USING btree ("custom_font_file_id");
  CREATE INDEX IF NOT EXISTS "_pages_v_blocks_career4_custom_font_file_idx" ON "_pages_v_blocks_career4" USING btree ("custom_font_file_id");
  CREATE INDEX IF NOT EXISTS "_pages_v_blocks_career5_custom_font_file_idx" ON "_pages_v_blocks_career5" USING btree ("custom_font_file_id");
  CREATE INDEX IF NOT EXISTS "_pages_v_blocks_career6_custom_font_file_idx" ON "_pages_v_blocks_career6" USING btree ("custom_font_file_id");
  CREATE INDEX IF NOT EXISTS "_pages_v_blocks_career_section1_custom_font_file_idx" ON "_pages_v_blocks_career_section1" USING btree ("custom_font_file_id");
  `)

  // 5. DROP COLUMN IF EXISTS (columnas antiguas)
  await db.execute(sql`
  ALTER TABLE "pages_blocks_career4_depts4_jobs" DROP COLUMN IF EXISTS "title";
  ALTER TABLE "pages_blocks_career4_depts4_jobs" DROP COLUMN IF EXISTS "location";
  ALTER TABLE "pages_blocks_career4_depts4_jobs" DROP COLUMN IF EXISTS "description";
  ALTER TABLE "pages_blocks_career4" DROP COLUMN IF EXISTS "tagline";
  ALTER TABLE "pages_blocks_career4" DROP COLUMN IF EXISTS "heading";
  ALTER TABLE "pages_blocks_career4" DROP COLUMN IF EXISTS "description";
  ALTER TABLE "career5_jobs" DROP COLUMN IF EXISTS "title";
  ALTER TABLE "career5_jobs" DROP COLUMN IF EXISTS "location";
  ALTER TABLE "career5_jobs" DROP COLUMN IF EXISTS "description";
  ALTER TABLE "pages_blocks_career5" DROP COLUMN IF EXISTS "tagline";
  ALTER TABLE "pages_blocks_career5" DROP COLUMN IF EXISTS "heading";
  ALTER TABLE "pages_blocks_career5" DROP COLUMN IF EXISTS "description";
  ALTER TABLE "career6_jobs" DROP COLUMN IF EXISTS "title";
  ALTER TABLE "career6_jobs" DROP COLUMN IF EXISTS "location";
  ALTER TABLE "career6_jobs" DROP COLUMN IF EXISTS "description";
  ALTER TABLE "pages_blocks_career6" DROP COLUMN IF EXISTS "tagline";
  ALTER TABLE "pages_blocks_career6" DROP COLUMN IF EXISTS "heading";
  ALTER TABLE "pages_blocks_career6" DROP COLUMN IF EXISTS "description";
  ALTER TABLE "jobs" DROP COLUMN IF EXISTS "title";
  ALTER TABLE "jobs" DROP COLUMN IF EXISTS "location";
  ALTER TABLE "jobs" DROP COLUMN IF EXISTS "description";
  ALTER TABLE "jobs" DROP COLUMN IF EXISTS "url";
  ALTER TABLE "pages_blocks_career_section1" DROP COLUMN IF EXISTS "tagline";
  ALTER TABLE "pages_blocks_career_section1" DROP COLUMN IF EXISTS "heading";
  ALTER TABLE "pages_blocks_career_section1" DROP COLUMN IF EXISTS "description";
  ALTER TABLE "_pages_v_blocks_career4_depts4_jobs" DROP COLUMN IF EXISTS "title";
  ALTER TABLE "_pages_v_blocks_career4_depts4_jobs" DROP COLUMN IF EXISTS "location";
  ALTER TABLE "_pages_v_blocks_career4_depts4_jobs" DROP COLUMN IF EXISTS "description";
  ALTER TABLE "_pages_v_blocks_career4" DROP COLUMN IF EXISTS "tagline";
  ALTER TABLE "_pages_v_blocks_career4" DROP COLUMN IF EXISTS "heading";
  ALTER TABLE "_pages_v_blocks_career4" DROP COLUMN IF EXISTS "description";
  ALTER TABLE "_career5_jobs_v" DROP COLUMN IF EXISTS "title";
  ALTER TABLE "_career5_jobs_v" DROP COLUMN IF EXISTS "location";
  ALTER TABLE "_career5_jobs_v" DROP COLUMN IF EXISTS "description";
  ALTER TABLE "_pages_v_blocks_career5" DROP COLUMN IF EXISTS "tagline";
  ALTER TABLE "_pages_v_blocks_career5" DROP COLUMN IF EXISTS "heading";
  ALTER TABLE "_pages_v_blocks_career5" DROP COLUMN IF EXISTS "description";
  ALTER TABLE "_career6_jobs_v" DROP COLUMN IF EXISTS "title";
  ALTER TABLE "_career6_jobs_v" DROP COLUMN IF EXISTS "location";
  ALTER TABLE "_career6_jobs_v" DROP COLUMN IF EXISTS "description";
  ALTER TABLE "_pages_v_blocks_career6" DROP COLUMN IF EXISTS "tagline";
  ALTER TABLE "_pages_v_blocks_career6" DROP COLUMN IF EXISTS "heading";
  ALTER TABLE "_pages_v_blocks_career6" DROP COLUMN IF EXISTS "description";
  ALTER TABLE "_jobs_v" DROP COLUMN IF EXISTS "title";
  ALTER TABLE "_jobs_v" DROP COLUMN IF EXISTS "location";
  ALTER TABLE "_jobs_v" DROP COLUMN IF EXISTS "description";
  ALTER TABLE "_jobs_v" DROP COLUMN IF EXISTS "url";
  ALTER TABLE "_pages_v_blocks_career_section1" DROP COLUMN IF EXISTS "tagline";
  ALTER TABLE "_pages_v_blocks_career_section1" DROP COLUMN IF EXISTS "heading";
  ALTER TABLE "_pages_v_blocks_career_section1" DROP COLUMN IF EXISTS "description";
  `)
}

export async function down({ db, payload, req }: MigrateDownArgs): Promise<void> {
  await db.execute(sql`
   ALTER TABLE "pages_blocks_career4" DROP CONSTRAINT IF EXISTS "pages_blocks_career4_custom_font_file_id_fonts_id_fk";
   ALTER TABLE "pages_blocks_career5" DROP CONSTRAINT IF EXISTS "pages_blocks_career5_custom_font_file_id_fonts_id_fk";
   ALTER TABLE "pages_blocks_career6" DROP CONSTRAINT IF EXISTS "pages_blocks_career6_custom_font_file_id_fonts_id_fk";
   ALTER TABLE "pages_blocks_career_section1" DROP CONSTRAINT IF EXISTS "pages_blocks_career_section1_custom_font_file_id_fonts_id_fk";
   ALTER TABLE "_pages_v_blocks_career4" DROP CONSTRAINT IF EXISTS "_pages_v_blocks_career4_custom_font_file_id_fonts_id_fk";
   ALTER TABLE "_pages_v_blocks_career5" DROP CONSTRAINT IF EXISTS "_pages_v_blocks_career5_custom_font_file_id_fonts_id_fk";
   ALTER TABLE "_pages_v_blocks_career6" DROP CONSTRAINT IF EXISTS "_pages_v_blocks_career6_custom_font_file_id_fonts_id_fk";
   ALTER TABLE "_pages_v_blocks_career_section1" DROP CONSTRAINT IF EXISTS "_pages_v_blocks_career_section1_custom_font_file_id_fonts_id_fk";
   DROP INDEX IF EXISTS "pages_blocks_career4_custom_font_file_idx";
   DROP INDEX IF EXISTS "pages_blocks_career5_custom_font_file_idx";
   DROP INDEX IF EXISTS "pages_blocks_career6_custom_font_file_idx";
   DROP INDEX IF EXISTS "pages_blocks_career_section1_custom_font_file_idx";
   DROP INDEX IF EXISTS "_pages_v_blocks_career4_custom_font_file_idx";
   DROP INDEX IF EXISTS "_pages_v_blocks_career5_custom_font_file_idx";
   DROP INDEX IF EXISTS "_pages_v_blocks_career6_custom_font_file_idx";
   DROP INDEX IF EXISTS "_pages_v_blocks_career_section1_custom_font_file_idx";
  `)
  await db.execute(sql`
   ALTER TABLE "pages_blocks_career4_depts4_jobs" ALTER COLUMN "url" SET DEFAULT '#';
   ALTER TABLE "pages_blocks_career4_depts4" ALTER COLUMN "title" SET DATA TYPE varchar USING (title::text);
   ALTER TABLE "pages_blocks_career4_depts4" ALTER COLUMN "title" SET DEFAULT 'Job Department';
   ALTER TABLE "career5_depts" ALTER COLUMN "title" SET DATA TYPE varchar USING (title::text);
   ALTER TABLE "career5_depts" ALTER COLUMN "title" SET DEFAULT 'Job Department';
   ALTER TABLE "career6_depts" ALTER COLUMN "title" SET DATA TYPE varchar USING (title::text);
   ALTER TABLE "career6_depts" ALTER COLUMN "title" SET DEFAULT 'Job Department';
   ALTER TABLE "depts" ALTER COLUMN "title" SET DATA TYPE varchar USING (title::text);
   ALTER TABLE "depts" ALTER COLUMN "title" SET DEFAULT 'Job Department';
   ALTER TABLE "_pages_v_blocks_career4_depts4_jobs" ALTER COLUMN "url" SET DEFAULT '#';
   ALTER TABLE "_pages_v_blocks_career4_depts4" ALTER COLUMN "title" SET DATA TYPE varchar USING (title::text);
   ALTER TABLE "_pages_v_blocks_career4_depts4" ALTER COLUMN "title" SET DEFAULT 'Job Department';
   ALTER TABLE "_career5_depts_v" ALTER COLUMN "title" SET DATA TYPE varchar USING (title::text);
   ALTER TABLE "_career5_depts_v" ALTER COLUMN "title" SET DEFAULT 'Job Department';
   ALTER TABLE "_career6_depts_v" ALTER COLUMN "title" SET DATA TYPE varchar USING (title::text);
   ALTER TABLE "_career6_depts_v" ALTER COLUMN "title" SET DEFAULT 'Job Department';
   ALTER TABLE "_depts_v" ALTER COLUMN "title" SET DATA TYPE varchar USING (title::text);
   ALTER TABLE "_depts_v" ALTER COLUMN "title" SET DEFAULT 'Job Department';
  `)
  await db.execute(sql`
   ALTER TABLE "pages_blocks_career4_depts4_jobs" ADD COLUMN "title" varchar DEFAULT 'Job Title';
   ALTER TABLE "pages_blocks_career4_depts4_jobs" ADD COLUMN "location" varchar DEFAULT 'Location';
   ALTER TABLE "pages_blocks_career4_depts4_jobs" ADD COLUMN "description" varchar DEFAULT 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse varius enim in eros elementum tristique. Duis cursus, mi quis viverra ornare, eros dolor interdum nulla, ut commodo diam libero vitae erat. Aenean faucibus nibh et justo cursus id rutrum lorem imperdiet. Nunc ut sem vitae risus tristique posuere.';
   ALTER TABLE "pages_blocks_career4" ADD COLUMN "tagline" varchar DEFAULT 'Tagline';
   ALTER TABLE "pages_blocks_career4" ADD COLUMN "heading" varchar DEFAULT 'Job Openings';
   ALTER TABLE "pages_blocks_career4" ADD COLUMN "description" varchar DEFAULT 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse varius enim in eros elementum tristique.';
   ALTER TABLE "career5_jobs" ADD COLUMN "title" varchar DEFAULT 'Job Title';
   ALTER TABLE "career5_jobs" ADD COLUMN "location" varchar DEFAULT 'Location';
   ALTER TABLE "career5_jobs" ADD COLUMN "description" varchar DEFAULT 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse varius enim in eros elementum tristique. Duis cursus, mi quis viverra ornare, eros dolor interdum nulla, ut commodo diam libero vitae erat. Aenean faucibus nibh et justo cursus id rutrum lorem imperdiet. Nunc ut sem vitae risus tristique posuere.';
   ALTER TABLE "pages_blocks_career5" ADD COLUMN "tagline" varchar DEFAULT 'Tagline';
   ALTER TABLE "pages_blocks_career5" ADD COLUMN "heading" varchar DEFAULT 'Job Openings';
   ALTER TABLE "pages_blocks_career5" ADD COLUMN "description" varchar DEFAULT 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse varius enim in eros elementum tristique.';
   ALTER TABLE "career6_jobs" ADD COLUMN "title" varchar DEFAULT 'Job Title';
   ALTER TABLE "career6_jobs" ADD COLUMN "location" varchar DEFAULT 'Location';
   ALTER TABLE "career6_jobs" ADD COLUMN "description" varchar DEFAULT 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse varius enim in eros elementum tristique. Duis cursus, mi quis viverra ornare, eros dolor interdum nulla, ut commodo diam libero vitae erat. Aenean faucibus nibh et justo cursus id rutrum lorem imperdiet. Nunc ut sem vitae risus tristique posuere.';
   ALTER TABLE "pages_blocks_career6" ADD COLUMN "tagline" varchar DEFAULT 'Tagline';
   ALTER TABLE "pages_blocks_career6" ADD COLUMN "heading" varchar DEFAULT 'Job Openings';
   ALTER TABLE "pages_blocks_career6" ADD COLUMN "description" varchar DEFAULT 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse varius enim in eros elementum tristique.';
   ALTER TABLE "jobs" ADD COLUMN "title" varchar DEFAULT 'Job Title';
   ALTER TABLE "jobs" ADD COLUMN "location" varchar DEFAULT 'Location';
   ALTER TABLE "jobs" ADD COLUMN "description" varchar DEFAULT 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse varius enim in eros elementum tristique. Duis cursus, mi quis viverra ornare, eros dolor interdum nulla, ut commodo diam libero vitae erat. Aenean faucibus nibh et justo cursus id rutrum lorem imperdiet. Nunc ut sem vitae risus tristique posuere.';
   ALTER TABLE "jobs" ADD COLUMN "url" varchar DEFAULT '#';
   ALTER TABLE "pages_blocks_career_section1" ADD COLUMN "tagline" varchar DEFAULT 'Tagline';
   ALTER TABLE "pages_blocks_career_section1" ADD COLUMN "heading" varchar DEFAULT 'Job Openings';
   ALTER TABLE "pages_blocks_career_section1" ADD COLUMN "description" varchar DEFAULT 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse varius enim in eros elementum tristique.';
   ALTER TABLE "_pages_v_blocks_career4_depts4_jobs" ADD COLUMN "title" varchar DEFAULT 'Job Title';
   ALTER TABLE "_pages_v_blocks_career4_depts4_jobs" ADD COLUMN "location" varchar DEFAULT 'Location';
   ALTER TABLE "_pages_v_blocks_career4_depts4_jobs" ADD COLUMN "description" varchar DEFAULT 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse varius enim in eros elementum tristique. Duis cursus, mi quis viverra ornare, eros dolor interdum nulla, ut commodo diam libero vitae erat. Aenean faucibus nibh et justo cursus id rutrum lorem imperdiet. Nunc ut sem vitae risus tristique posuere.';
   ALTER TABLE "_pages_v_blocks_career4" ADD COLUMN "tagline" varchar DEFAULT 'Tagline';
   ALTER TABLE "_pages_v_blocks_career4" ADD COLUMN "heading" varchar DEFAULT 'Job Openings';
   ALTER TABLE "_pages_v_blocks_career4" ADD COLUMN "description" varchar DEFAULT 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse varius enim in eros elementum tristique.';
   ALTER TABLE "_career5_jobs_v" ADD COLUMN "title" varchar DEFAULT 'Job Title';
   ALTER TABLE "_career5_jobs_v" ADD COLUMN "location" varchar DEFAULT 'Location';
   ALTER TABLE "_career5_jobs_v" ADD COLUMN "description" varchar DEFAULT 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse varius enim in eros elementum tristique. Duis cursus, mi quis viverra ornare, eros dolor interdum nulla, ut commodo diam libero vitae erat. Aenean faucibus nibh et justo cursus id rutrum lorem imperdiet. Nunc ut sem vitae risus tristique posuere.';
   ALTER TABLE "_pages_v_blocks_career5" ADD COLUMN "tagline" varchar DEFAULT 'Tagline';
   ALTER TABLE "_pages_v_blocks_career5" ADD COLUMN "heading" varchar DEFAULT 'Job Openings';
   ALTER TABLE "_pages_v_blocks_career5" ADD COLUMN "description" varchar DEFAULT 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse varius enim in eros elementum tristique.';
   ALTER TABLE "_career6_jobs_v" ADD COLUMN "title" varchar DEFAULT 'Job Title';
   ALTER TABLE "_career6_jobs_v" ADD COLUMN "location" varchar DEFAULT 'Location';
   ALTER TABLE "_career6_jobs_v" ADD COLUMN "description" varchar DEFAULT 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse varius enim in eros elementum tristique. Duis cursus, mi quis viverra ornare, eros dolor interdum nulla, ut commodo diam libero vitae erat. Aenean faucibus nibh et justo cursus id rutrum lorem imperdiet. Nunc ut sem vitae risus tristique posuere.';
   ALTER TABLE "_pages_v_blocks_career6" ADD COLUMN "tagline" varchar DEFAULT 'Tagline';
   ALTER TABLE "_pages_v_blocks_career6" ADD COLUMN "heading" varchar DEFAULT 'Job Openings';
   ALTER TABLE "_pages_v_blocks_career6" ADD COLUMN "description" varchar DEFAULT 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse varius enim in eros elementum tristique.';
   ALTER TABLE "_jobs_v" ADD COLUMN "title" varchar DEFAULT 'Job Title';
   ALTER TABLE "_jobs_v" ADD COLUMN "location" varchar DEFAULT 'Location';
   ALTER TABLE "_jobs_v" ADD COLUMN "description" varchar DEFAULT 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse varius enim in eros elementum tristique. Duis cursus, mi quis viverra ornare, eros dolor interdum nulla, ut commodo diam libero vitae erat. Aenean faucibus nibh et justo cursus id rutrum lorem imperdiet. Nunc ut sem vitae risus tristique posuere.';
   ALTER TABLE "_jobs_v" ADD COLUMN "url" varchar DEFAULT '#';
   ALTER TABLE "_pages_v_blocks_career_section1" ADD COLUMN "tagline" varchar DEFAULT 'Tagline';
   ALTER TABLE "_pages_v_blocks_career_section1" ADD COLUMN "heading" varchar DEFAULT 'Job Openings';
   ALTER TABLE "_pages_v_blocks_career_section1" ADD COLUMN "description" varchar DEFAULT 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse varius enim in eros elementum tristique.';
  `)
  await db.execute(sql`
   ALTER TABLE "pages_blocks_career4_depts4_jobs" DROP COLUMN "job_content";
   ALTER TABLE "pages_blocks_career4_depts4_jobs" DROP COLUMN "type";
   ALTER TABLE "pages_blocks_career4_depts4_jobs" DROP COLUMN "new_tab";
   ALTER TABLE "pages_blocks_career4" DROP COLUMN "content";
   ALTER TABLE "pages_blocks_career4" DROP COLUMN "background_color";
   ALTER TABLE "pages_blocks_career4" DROP COLUMN "text_color";
   ALTER TABLE "pages_blocks_career4" DROP COLUMN "bold_text_color";
   ALTER TABLE "pages_blocks_career4" DROP COLUMN "button_background_color";
   ALTER TABLE "pages_blocks_career4" DROP COLUMN "button_text_color";
   ALTER TABLE "pages_blocks_career4" DROP COLUMN "font_family";
   ALTER TABLE "pages_blocks_career4" DROP COLUMN "use_custom_font";
   ALTER TABLE "pages_blocks_career4" DROP COLUMN "custom_font_file_id";
   ALTER TABLE "pages_blocks_career4" DROP COLUMN "custom_font_name";
   ALTER TABLE "career5_jobs" DROP COLUMN "job_content";
   ALTER TABLE "pages_blocks_career5" DROP COLUMN "content";
   ALTER TABLE "pages_blocks_career5" DROP COLUMN "background_color";
   ALTER TABLE "pages_blocks_career5" DROP COLUMN "text_color";
   ALTER TABLE "pages_blocks_career5" DROP COLUMN "bold_text_color";
   ALTER TABLE "pages_blocks_career5" DROP COLUMN "button_background_color";
   ALTER TABLE "pages_blocks_career5" DROP COLUMN "button_text_color";
   ALTER TABLE "pages_blocks_career5" DROP COLUMN "font_family";
   ALTER TABLE "pages_blocks_career5" DROP COLUMN "use_custom_font";
   ALTER TABLE "pages_blocks_career5" DROP COLUMN "custom_font_file_id";
   ALTER TABLE "pages_blocks_career5" DROP COLUMN "custom_font_name";
   ALTER TABLE "career6_jobs" DROP COLUMN "job_content";
   ALTER TABLE "pages_blocks_career6" DROP COLUMN "content";
   ALTER TABLE "pages_blocks_career6" DROP COLUMN "background_color";
   ALTER TABLE "pages_blocks_career6" DROP COLUMN "text_color";
   ALTER TABLE "pages_blocks_career6" DROP COLUMN "bold_text_color";
   ALTER TABLE "pages_blocks_career6" DROP COLUMN "button_background_color";
   ALTER TABLE "pages_blocks_career6" DROP COLUMN "button_text_color";
   ALTER TABLE "pages_blocks_career6" DROP COLUMN "font_family";
   ALTER TABLE "pages_blocks_career6" DROP COLUMN "use_custom_font";
   ALTER TABLE "pages_blocks_career6" DROP COLUMN "custom_font_file_id";
   ALTER TABLE "pages_blocks_career6" DROP COLUMN "custom_font_name";
   ALTER TABLE "jobs" DROP COLUMN "job_content";
   ALTER TABLE "jobs" DROP COLUMN "link_type";
   ALTER TABLE "jobs" DROP COLUMN "link_new_tab";
   ALTER TABLE "jobs" DROP COLUMN "link_url";
   ALTER TABLE "pages_blocks_career_section1" DROP COLUMN "content";
   ALTER TABLE "pages_blocks_career_section1" DROP COLUMN "background_color";
   ALTER TABLE "pages_blocks_career_section1" DROP COLUMN "text_color";
   ALTER TABLE "pages_blocks_career_section1" DROP COLUMN "bold_text_color";
   ALTER TABLE "pages_blocks_career_section1" DROP COLUMN "button_background_color";
   ALTER TABLE "pages_blocks_career_section1" DROP COLUMN "button_text_color";
   ALTER TABLE "pages_blocks_career_section1" DROP COLUMN "font_family";
   ALTER TABLE "pages_blocks_career_section1" DROP COLUMN "use_custom_font";
   ALTER TABLE "pages_blocks_career_section1" DROP COLUMN "custom_font_file_id";
   ALTER TABLE "pages_blocks_career_section1" DROP COLUMN "custom_font_name";
   ALTER TABLE "_pages_v_blocks_career4_depts4_jobs" DROP COLUMN "job_content";
   ALTER TABLE "_pages_v_blocks_career4_depts4_jobs" DROP COLUMN "type";
   ALTER TABLE "_pages_v_blocks_career4_depts4_jobs" DROP COLUMN "new_tab";
   ALTER TABLE "_pages_v_blocks_career4" DROP COLUMN "content";
   ALTER TABLE "_pages_v_blocks_career4" DROP COLUMN "background_color";
   ALTER TABLE "_pages_v_blocks_career4" DROP COLUMN "text_color";
   ALTER TABLE "_pages_v_blocks_career4" DROP COLUMN "bold_text_color";
   ALTER TABLE "_pages_v_blocks_career4" DROP COLUMN "button_background_color";
   ALTER TABLE "_pages_v_blocks_career4" DROP COLUMN "button_text_color";
   ALTER TABLE "_pages_v_blocks_career4" DROP COLUMN "font_family";
   ALTER TABLE "_pages_v_blocks_career4" DROP COLUMN "use_custom_font";
   ALTER TABLE "_pages_v_blocks_career4" DROP COLUMN "custom_font_file_id";
   ALTER TABLE "_pages_v_blocks_career4" DROP COLUMN "custom_font_name";
   ALTER TABLE "_career5_jobs_v" DROP COLUMN "job_content";
   ALTER TABLE "_pages_v_blocks_career5" DROP COLUMN "content";
   ALTER TABLE "_pages_v_blocks_career5" DROP COLUMN "background_color";
   ALTER TABLE "_pages_v_blocks_career5" DROP COLUMN "text_color";
   ALTER TABLE "_pages_v_blocks_career5" DROP COLUMN "bold_text_color";
   ALTER TABLE "_pages_v_blocks_career5" DROP COLUMN "button_background_color";
   ALTER TABLE "_pages_v_blocks_career5" DROP COLUMN "button_text_color";
   ALTER TABLE "_pages_v_blocks_career5" DROP COLUMN "font_family";
   ALTER TABLE "_pages_v_blocks_career5" DROP COLUMN "use_custom_font";
   ALTER TABLE "_pages_v_blocks_career5" DROP COLUMN "custom_font_file_id";
   ALTER TABLE "_pages_v_blocks_career5" DROP COLUMN "custom_font_name";
   ALTER TABLE "_career6_jobs_v" DROP COLUMN "job_content";
   ALTER TABLE "_pages_v_blocks_career6" DROP COLUMN "content";
   ALTER TABLE "_pages_v_blocks_career6" DROP COLUMN "background_color";
   ALTER TABLE "_pages_v_blocks_career6" DROP COLUMN "text_color";
   ALTER TABLE "_pages_v_blocks_career6" DROP COLUMN "bold_text_color";
   ALTER TABLE "_pages_v_blocks_career6" DROP COLUMN "button_background_color";
   ALTER TABLE "_pages_v_blocks_career6" DROP COLUMN "button_text_color";
   ALTER TABLE "_pages_v_blocks_career6" DROP COLUMN "font_family";
   ALTER TABLE "_pages_v_blocks_career6" DROP COLUMN "use_custom_font";
   ALTER TABLE "_pages_v_blocks_career6" DROP COLUMN "custom_font_file_id";
   ALTER TABLE "_pages_v_blocks_career6" DROP COLUMN "custom_font_name";
   ALTER TABLE "_jobs_v" DROP COLUMN "job_content";
   ALTER TABLE "_jobs_v" DROP COLUMN "link_type";
   ALTER TABLE "_jobs_v" DROP COLUMN "link_new_tab";
   ALTER TABLE "_jobs_v" DROP COLUMN "link_url";
   ALTER TABLE "_pages_v_blocks_career_section1" DROP COLUMN "content";
   ALTER TABLE "_pages_v_blocks_career_section1" DROP COLUMN "background_color";
   ALTER TABLE "_pages_v_blocks_career_section1" DROP COLUMN "text_color";
   ALTER TABLE "_pages_v_blocks_career_section1" DROP COLUMN "bold_text_color";
   ALTER TABLE "_pages_v_blocks_career_section1" DROP COLUMN "button_background_color";
   ALTER TABLE "_pages_v_blocks_career_section1" DROP COLUMN "button_text_color";
   ALTER TABLE "_pages_v_blocks_career_section1" DROP COLUMN "font_family";
   ALTER TABLE "_pages_v_blocks_career_section1" DROP COLUMN "use_custom_font";
   ALTER TABLE "_pages_v_blocks_career_section1" DROP COLUMN "custom_font_file_id";
   ALTER TABLE "_pages_v_blocks_career_section1" DROP COLUMN "custom_font_name";
   DROP TYPE "public"."enum_pages_blocks_career4_depts4_jobs_type";
   DROP TYPE "public"."enum_pages_blocks_career4_font_family";
   DROP TYPE "public"."enum_pages_blocks_career5_font_family";
   DROP TYPE "public"."enum_pages_blocks_career6_font_family";
   DROP TYPE "public"."enum_jobs_link_type";
   DROP TYPE "public"."enum_pages_blocks_career_section1_font_family";
   DROP TYPE "public"."enum__pages_v_blocks_career4_depts4_jobs_type";
   DROP TYPE "public"."enum__pages_v_blocks_career4_font_family";
   DROP TYPE "public"."enum__pages_v_blocks_career5_font_family";
   DROP TYPE "public"."enum__pages_v_blocks_career6_font_family";
   DROP TYPE "public"."enum__jobs_v_link_type";
   DROP TYPE "public"."enum__pages_v_blocks_career_section1_font_family";
  `)
}
