import type { Block } from 'payload'

export const EventHeader3: Block = {
  slug: 'eventHeader3',
  dbName: 'evt_hdr_3',
  interfaceName: 'EventHeader3Block',
  fields: [
    {
      name: 'tagline',
      type: 'text',
      required: true,
      label: 'Tagline',
      defaultValue: 'Tagline',
    },
    {
      name: 'heading',
      type: 'text',
      required: true,
      label: 'Título Principal',
      defaultValue: 'Events',
    },
    {
      name: 'description',
      type: 'textarea',
      required: true,
      label: 'Descripción',
      defaultValue: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse varius enim in eros elementum tristique.',
    },
    {
      name: 'event',
      type: 'group',
      label: 'Evento Destacado',
      fields: [
        {
          name: 'url',
          type: 'text',
          required: true,
          label: 'URL del Evento',
          defaultValue: '#',
        },
        {
          name: 'image',
          type: 'upload',
          relationTo: 'media',
          required: false,
          label: 'Imagen del Evento',
        },
        {
          name: 'category',
          type: 'text',
          required: true,
          label: 'Categoría',
          defaultValue: 'Category',
        },
        {
          name: 'status',
          type: 'text',
          label: 'Estado (opcional)',
          admin: {
            description: 'Dejar vacío si no hay estado especial',
          },
        },
        {
          name: 'title',
          type: 'text',
          required: true,
          label: 'Título del Evento',
          defaultValue: 'Event title heading',
        },
        {
          name: 'date',
          type: 'group',
          label: 'Fecha del Evento',
          fields: [
            {
              name: 'weekday',
              type: 'text',
              required: true,
              label: 'Día de la Semana',
              defaultValue: 'Sat',
            },
            {
              name: 'day',
              type: 'text',
              required: true,
              label: 'Día',
              defaultValue: '10',
            },
            {
              name: 'month',
              type: 'text',
              required: true,
              label: 'Mes',
              defaultValue: 'Feb',
            },
            {
              name: 'year',
              type: 'text',
              required: true,
              label: 'Año',
              defaultValue: '2024',
            },
          ],
        },
        {
          name: 'location',
          type: 'text',
          required: true,
          label: 'Ubicación',
          defaultValue: 'Location',
        },
        {
          name: 'description',
          type: 'textarea',
          required: true,
          label: 'Descripción del Evento',
          defaultValue: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse varius enim in eros.',
        },
        {
          name: 'button',
          type: 'group',
          label: 'Configuración del Botón',
          fields: [
            {
              name: 'title',
              type: 'text',
              required: true,
              label: 'Texto del Botón',
              defaultValue: 'View event',
            },
            {
              name: 'url',
              type: 'text',
              required: true,
              label: 'URL del Botón',
              defaultValue: '#',
              admin: {
                description: 'Enlace al que dirigirá el botón al hacer clic',
              },
            },
            {
              name: 'variant',
              type: 'select',
              required: true,
              label: 'Variante del Botón',
              options: [
                { label: 'Primary', value: 'primary' },
                { label: 'Secondary', value: 'secondary' },
                { label: 'Link', value: 'link' },
                { label: 'Outline', value: 'outline' },
              ],
              defaultValue: 'link',
            },
            {
              name: 'size',
              type: 'select',
              required: true,
              label: 'Tamaño del Botón',
              options: [
                { label: 'Small', value: 'small' },
                { label: 'Medium', value: 'medium' },
                { label: 'Large', value: 'large' },
                { label: 'Primary', value: 'primary' },
                { label: 'Link', value: 'link' },
              ],
              defaultValue: 'link',
            },
          ],
        },
      ],
    },
    {
      name: 'featuredEvents',
      type: 'array',
      label: 'Eventos Destacados',
      fields: [
        {
          name: 'url',
          type: 'text',
          required: true,
          label: 'URL del Evento',
          defaultValue: '#',
        },
        {
          name: 'image',
          type: 'upload',
          relationTo: 'media',
          required: false,
          label: 'Imagen del Evento',
        },
        {
          name: 'status',
          type: 'text',
          label: 'Estado (opcional)',
          admin: {
            description: 'Dejar vacío si no hay estado especial',
          },
        },
        {
          name: 'date',
          type: 'group',
          label: 'Fecha del Evento',
          fields: [
            {
              name: 'weekday',
              type: 'text',
              required: true,
              label: 'Día de la Semana',
              defaultValue: 'Fri',
            },
            {
              name: 'day',
              type: 'text',
              required: true,
              label: 'Día',
              defaultValue: '09',
            },
            {
              name: 'month',
              type: 'text',
              required: true,
              label: 'Mes',
              defaultValue: 'Feb',
            },
            {
              name: 'year',
              type: 'text',
              required: true,
              label: 'Año',
              defaultValue: '2024',
            },
          ],
        },
        {
          name: 'location',
          type: 'text',
          required: true,
          label: 'Ubicación',
          defaultValue: 'Location',
        },
        {
          name: 'title',
          type: 'text',
          required: true,
          label: 'Título del Evento',
          defaultValue: 'Event title heading',
        },
        {
          name: 'description',
          type: 'textarea',
          required: true,
          label: 'Descripción del Evento',
          defaultValue: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse varius enim in eros elementum tristique.',
        },
        {
          name: 'button',
          type: 'group',
          label: 'Configuración del Botón',
          fields: [
            {
              name: 'title',
              type: 'text',
              required: true,
              label: 'Texto del Botón',
              defaultValue: 'View event',
            },
            {
              name: 'url',
              type: 'text',
              required: true,
              label: 'URL del Botón',
              defaultValue: '#',
              admin: {
                description: 'Enlace al que dirigirá el botón al hacer clic',
              },
            },
            {
              name: 'variant',
              type: 'select',
              required: true,
              label: 'Variante del Botón',
              options: [
                { label: 'Primary', value: 'primary' },
                { label: 'Secondary', value: 'secondary' },
                { label: 'Link', value: 'link' },
                { label: 'Outline', value: 'outline' },
              ],
              defaultValue: 'link',
            },
            {
              name: 'size',
              type: 'select',
              required: true,
              label: 'Tamaño del Botón',
              options: [
                { label: 'Small', value: 'small' },
                { label: 'Medium', value: 'medium' },
                { label: 'Large', value: 'large' },
                { label: 'Primary', value: 'primary' },
                { label: 'Link', value: 'link' },
              ],
              defaultValue: 'link',
            },
          ],
        },
      ],
    },
  ],
  labels: {
    plural: 'Event Headers 3',
    singular: 'Event Header 3',
  },
}
